### ISSUE TITLE
Refactor BUILD_VERSION

### ISSUE THREAD

**Issue by dharding** [covid-alert-ny/covid-green-app#1]
In order to avoid having to remember to update the build/marketing version of the app in multiple places, we should refactor how we set the version to be set in a single place and then referenced in all appropriate places (e.g. build.gradle, xcode project, app version display).

**Comment by colmharte** [comment]
@dharding any suggestions on how best to do this?

**Comment by fahd-arshad** [comment]
This is the proper fix to the manual workaround that @dharding will do in https://github.com/project-vagabond/covid-green-app/issues/91.
