### ISSUE TITLE
Contact Tracing Follow-up Call "Yes I want to opt-in" button active with no phone number entered

### ISSUE THREAD

**Issue by dharding** [covid-alert-ny/covid-green-app#10]
iPhone SE
I entered a new country code and the "Yes I want to opt-in" button became active even though the phone number field was still blank.

Before I changed the country code, the button is not active.

![IMG_0552_ContactTracingFollouUpSetUp-02](https://user-images.githubusercontent.com/6312392/88440363-bcf62000-cddb-11ea-8b09-3baec51cdf7d.PNG)

After I changed the country code, but before entering a phone number, the button became active prematurely.

![IMG_0568](https://user-images.githubusercontent.com/6312392/88440305-9a640700-cddb-11ea-917e-9b5a7584d79d.PNG)

**Comment by fahd-arshad** [comment]
We are no longer offering call-back so closing this.
