### ISSUE TITLE
Updates to Proximity Alert Drill in Screen

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#110]
Update the Proximity Alert drill-in screen as follows:

- [x] Move the self-isolation instructions + button to place a call the hotline to the landing screen of the Proximity notification. 

- [x] Add a new paragraph to the instructions to motivate users to consider getting a test.  The hyperlink should point to this URL: https://coronavirus.health.ny.gov/find-test-site-near-you.  This new paragraph needs to be added to all other instances of the "Learn How to Keep Others Safe" instructions: this work is captured as a separate ticket at https://github.com/project-vagabond/covid-green-app/issues/111

- [x] As a result of this, we should remove the following from the proximity alert landing page (only): 1) the button to drill into the "Learn how to keep others safe" instructions 2) the "OK" button at the bottom of proximity alert landing page. Note: As I haven't been able to see these in the build yet, it is possible that neither of these buttons have been implemented yet. If so, we can ignore this bullet.

Stuart is creating a new "Testing" icon, and we'll get these updates into Zeplin, but here's a quick screen-grab to help visualize:

![image](https://user-images.githubusercontent.com/68069959/91478807-7da17000-e86e-11ea-9df9-43dc3ea1cd20.png)

**Comment by AlanSl** [comment]
@floridemai We're missing the "Get tested" section, is that intentional?

**Comment by floridemai** [comment]
@ahurworth This should be now available in the next build. (18 i believe)

**Comment by ahurworth** [comment]
I see it :). Thanks @floridemai
