### ISSUE TITLE
Add a new item to all instances of the "keep safe" Instructions

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#111]
All instances of the "keep safe" instructions should be updated to show a new paragraph to the instructions to motivate users to consider getting a test. The hyperlink should point to this URL: https://coronavirus.health.ny.gov/find-test-site-near-you. It should be positioned as the penultimate instruction in this list, above the symptoms monitoring paragraph.  

Stuart is helping to produce an icon and will update Zeplin.

A quick visual for reference:
![image](https://user-images.githubusercontent.com/68069959/91479635-c1e14000-e86f-11ea-88d2-2cfde2c9c879.png)

**Comment by stuartgiles** [comment]
Here is the missing icon for "Getting tested"

[health-advice.zip](https://github.com/project-vagabond/covid-green-app/files/5142550/health-advice.zip)

**Comment by ahurworth** [comment]
Looks good, thanks.
