### ISSUE TITLE
DOH UAT - Data missing for 6 NYS Counties

### ISSUE THREAD

**Issue by kevin-sheldon** [covid-alert-ny/covid-green-app#112]
On NY COVID Data tab, there is no data for Warren, Washington, Wayne, Westchester, Wyoming, and Yates Counties. 

App originally crashed when these counties were selected. A fix was put in to prevent app from crashing if there is no data, but the data for these counties is still missing.

**Comment by AlanSl** [comment]
This is fixed on the `dev` API (see example screenshot for Wayne), so will be fixed when that update reaches the production API.

<img width=400 src="https://user-images.githubusercontent.com/29628323/91493899-e4934900-e8af-11ea-898e-faeadec37a50.jpg" />

**Comment by floridemai** [comment]
@mikegwhit Can you re-assign this back to Kevin when the prod api data is correct? Thanks

**Comment by mikegwhit** [comment]
This issue should have been fixed CC @kevin-sheldon 

We may still need to push to prod.

**Comment by kevin-sheldon** [comment]
I now see county data in the test app. Let me know if there is anything that the NF team needs to do before we close this.

**Comment by AlanSl** [comment]
@kevin-sheldon No, you can close this, thanks
