### ISSUE TITLE
DOH UAT - Y Axis Displays "1000" instead of "1K" causing 1000 label to be cut off

### ISSUE THREAD

**Issue by kevin-sheldon** [covid-alert-ny/covid-green-app#113]
On the NY COVID Data screen, any graph that displays the number "1000" on the Y-axis is cut off. Please change to "1k"

If you click on Albany county, this will show the bug.

**Comment by AlanSl** [comment]
Fixed in code, should be fixed in the next build (18?)

**Comment by kevin-sheldon** [comment]
retested and looks fine!
