### ISSUE TITLE
Change store presence to COVID Alert NY

### ISSUE THREAD

**Issue by mboskin** [covid-alert-ny/covid-green-app#115]
The name of the app has been finalized as: "COVID Alert NY"

- [x] Update store app name
- [x] Update store description
- [x] Update Android assets in store listing
- [x] Upload screenshots for iOS (if we have them, may want to wait until we are closer to final build)
- [x] Update privacy policy URL on Android store
- [x] Update privacy policy listing on iOS store

**Comment by stuartgiles** [comment]
Attached is a .zip file which contains all graphical assets required for the App and Play stores.
Please contact me or Antoine if anything is out of place.
[App promotion.zip](https://github.com/project-vagabond/covid-green-app/files/5142906/App.promotion.zip)
