### ISSUE TITLE
After Skipping Setup Unable to Turn on 'Use Exposure Notifications'

### ISSUE THREAD

**Issue by mboskin** [covid-alert-ny/covid-green-app#119]
In Get Started if you select Skip for now attempting to set up exposure notifications sends you to the settings page with a greyed out toggle with the notice "To turn on COVID-19 Exposure Notifications, finish setting up an available app". Deleting the data and going through the setup again allows it to work correctly.
--

**Comment by AlanSl** [comment]
@mboskin Is this on iOS or Android? (Sounds like Android?)

**Comment by mboskin** [comment]
Yes Android. A Galaxy S10+

_____________________

**Comment by floridemai** [comment]
This was indeed an bug, but in the older versions. In the current version, if you skip, you can go to "My COVID Alerts" tab, there will be a "Turn on" button which will prompt the ENS dialog.

**Comment by kevin-sheldon** [comment]
I retested this, and this looks fine now. Can enable right in app which is preferred.

**Comment by mboskin** [comment]
It’s issue 18 in the MS Teams issues log. Would you mind closing both?

Thanks,
Mike

_____________________


www.nystec.com<http://www.nystec.com/>
