### ISSUE TITLE
The HTML Entity Names/Numbers are showing up for certain characters in Data Protection Information Notice page.

### ISSUE THREAD

**Issue by mboskin** [covid-alert-ny/covid-green-app#123]
Android | Galaxy S6+ | 8/27/2020 5:00PM | Raghunath Gajjala

The characters Apostrophe(&#39;) and Quotes(&quot;) are showing up in Entity Name/Number format in Data Protection Information Notice page under App Settings>>Data and Privacy Policy

**Comment by colmharte** [comment]
This is an issue with the data on the server, assigning to @segfault

**Comment by AlanSl** [comment]
I've added some code to the app that decodes any HTML entities it receives. So it should be fixed in the next build (18?) and we're not dependent on it getting fixed on the server.

**Comment by fahd-arshad** [comment]
Looks good now.
