### ISSUE TITLE
Bugs/Suggested UI Enhancements to My Health Log page. 

### ISSUE THREAD

**Issue by mboskin** [covid-alert-ny/covid-green-app#124]
Android | Galaxy S6+ | 8/27/2020 5:30PM | Raghunath Gajjala

Suggested Enhancements:   1.) Clicking on the The NYS Health Hotline number in My Health Log page is not opening the Phone app as it did for call 911.    2.)The link ‘Find a site near you’ is too close to ‘call 911’ button in My Health Log page.

**Comment by AlanSl** [comment]
The telephone links were added yesteday and the spacing fix is going in today's build

**Comment by fahd-arshad** [comment]
I was able to validate that the phone number works on Android in build 22. 
Samsung Galaxy 10 (SM-G970U) Android 10 One UI 2.1

**Comment by mboskin** [comment]
Patrick Brennan | 9/1/20 5:23 PM | Pass
