### ISSUE TITLE
My COVID Alerts "Setup" Button Not Working to Enable Closeness Sensing

### ISSUE THREAD

**Issue by mboskin** [covid-alert-ny/covid-green-app#125]
Android | LG K40 | 8/27/20 5:22 PM | Francisco Torrales

unable to select Update settings on a 2nd attempt via My COVID Alerts in App Settings.   1 - turned off bluetooth on phone    2 - then went into App Settings, Status said it Closeness    Sensing is currently active    3 - I selected Update settings button where I then had to turn on    bluetooth via app.    4 - Selected back    5 - Went back into App Settings back in to see update but Update settings will not open.
--

**Comment by floridemai** [comment]
@mboskin I think this was happening on older versions. Do you know the version this was tested against?
Also... if I got the issue right, this is something that we're aware of and can't be  solved. But the phone should notify the user that  ENS is not active.
You can read more here: https://github.com/project-vagabond/covid-green-app/issues/8

**Comment by mboskin** [comment]
Issue that “can’t be solved”.

Inconsistent behavior when Bluetooth is disabled (Android and iOS)

_____________________
Michael Boskin
Senior Consultant, NYSTEC
(518) 496-7667 – Mobile
mboskin@nystec.com<mailto:mboskin@nystec.com>

www.nystec.com<http://www.nystec.com/>

**Comment by fahd-arshad** [comment]
Closing this ticket since we have an older #8 that has more detail on this issue. The specific problem of the "Update Settings" button that the tester found non-operational on Android has been fixed.
