### ISSUE TITLE
Integrate Firebase Remote Config

### ISSUE THREAD

**Issue by dharding** [covid-alert-ny/covid-green-app#13]
In order to be able to update the configuration of the app without releasing a new build to the app stores, we want to integrate with remote config. The app should fetch the latest remote config upon launch as well as when the app comes to the foreground.

**Comment by davidjharding** [comment]
Crashlytics and Remote Config are integrated. Remote Config only runs at app start for now as we do not have any configuration being managed in there. When we decide to add our first config setting, we will update the defaults in the app and set it to fetch on app foregrounding.
