### ISSUE TITLE
Chart Labels Are Not Getting Translated

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#144]
Chart labels are not getting translated - see screenshot.

County selector is missing translation, and there are some issues with tab labels, but these are covered by a separate ticket.  
 
![Chart Label Not Translated](https://user-images.githubusercontent.com/68069959/91601729-21a31e00-e938-11ea-9e5b-ef2cbb727640.png)

**Comment by mboskin** [comment]
Is this the same as issue 112?

**Comment by mboskin** [comment]
Since I did not create the issue I need to trace it back to Teams for the testers

**Comment by AlanSl** [comment]
Tab labels issue (rogue `/ n`s etc) is already covered and done, but I think we are missing some chart label translations. 

I'll add auto-translations for now

**Comment by ahurworth** [comment]
Thanks @AlanSl .  @mboskin to respond to your question - it's a different issue.

**Comment by AlanSl** [comment]
We should now be all up to date here except the new Positivity % chart which will be updated in the build after we get the updated translations sheet
