### ISSUE TITLE
Typo on Update Settings button

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#146]
Please capitalize the s in the word "Settings" on this button.  

![Screenshot_20200827-211346](https://user-images.githubusercontent.com/68069959/91605272-31256580-e93e-11ea-9d2c-74e0f84b8070.png)

**Comment by AlanSl** [comment]
Should be done in next build

**Comment by helloantoine** [comment]
It is done. Thank you Alan
