### ISSUE TITLE
Small Visual "Jumping" Happens on Tab Switch to My Health Log 

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#151]
Switching between tabs is working well for all tabs except for the Health Log.  If you keep your eye on the tab bar, you'll see it drops down by a few pixels when switching to the Health Log, creating a "jumping" effect.  I've captured this in this video:

I think this may be solved by making "My Health Log" two lines (insert the break after the word "Health"), which was part of the desired design anyway.  We should do this regardless of whether it solves the jumping issue.  

[20200829-072115-720x1520.mp4.zip](https://github.com/project-vagabond/covid-green-app/files/5145134/20200829-072115-720x1520.mp4.zip)

![Screenshot_20200829-071547](https://user-images.githubusercontent.com/68069959/91635574-91141e80-e9c7-11ea-9c21-cdedf9251d57.png)

**Comment by floridemai** [comment]
@ahurworth Can you re-check this in the next build?
