### ISSUE TITLE
As a user, I want to know when I've been in close contact with a COVID case, so that I can request help and know how to quarantine.

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#16]
(Changes to behavior)

**Comment by fahd-arshad** [comment]
@ahurworth can you kindly see if this issue can be closed?

**Comment by ahurworth** [comment]
Sure @fahd-arshad.  Would you, or someone else be able to generate a proximity alert for me so that I can test it in the build?

**Comment by ahurworth** [comment]
Through the debug tool, I'm not seeing this at all on Android.  On iPhone, I'm sometimes seeing it, but on tap, I'm not landing in the drilled in view.  It's just opening the app using its retained state.

**Comment by floridemai** [comment]
@ahurworth Can you re-check this in the next build? Thanks
