### ISSUE TITLE
iOS Versions Below Minimum Threshold Do Not Indicate Issues with Closeness Sensing During Onboarding

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#160]
I have an iPhone device (intentionally) running an outdated version of iOS (v11.1).  During on-boarding setup, there's no indication that Closeness Sensing isn't possible, or any prompt to update the OS during on-boarding.  The iOS System alert to enable ENS is simply skipped and the user is only prompted to enable Notifications.

Post-onboarding, I do see that the COVID Alerts tab's icon is correct, and so is the landing state within the COVID Alert tab, which is good news.

**Comment by floridemai** [comment]
@ahurworth That should not happen in the latest build. Can you record that and send it (here or private). I want to see if something's odd is happening on the transition. Also can you confirm that "My COVID Alerts" shows the check for updates notification?

**Comment by ahurworth** [comment]
It does thanks!  All appears to be working since build 21.  Thank you.
