### ISSUE TITLE
Usability issue. NY COVID Data tab. Graph not contrasted enough.

### ISSUE THREAD

**Issue by helloantoine** [covid-alert-ny/covid-green-app#169]
**Issue:**
![Image from iOS (2)](https://user-images.githubusercontent.com/16833643/91707942-79c86300-eb78-11ea-91a9-306f333c1333.png)
Orange and light gray on white background do not pass contrast checker.
Font size for the value of the left is too small. 

**Solution:** 
Increase font size slightly and colours. Mockup to be done.

**Comment by AlanSl** [comment]
@helloantoine Send me a colour for the bars and I'll get this done, just FYI I'll need to increase the amount of space given to the Y axis so might need to reduce the number of labels on the x axis

**Comment by helloantoine** [comment]
![colors](https://user-images.githubusercontent.com/16833643/91736498-a9da2b00-eba5-11ea-9109-5d4dbee3961c.png)
Final designs. Discussed with Alex. 

bars: #ACAFC4
line: #CD4000
outline: #FFF

**Comment by helloantoine** [comment]
![Image from iOS (1)](https://user-images.githubusercontent.com/16833643/91736924-54524e00-eba6-11ea-89e1-a23387aee94d.png)
Also. The 100k is cropped on the Y-Axis of the current graph.

**Comment by AlanSl** [comment]
Done in https://github.com/project-vagabond/covid-green-app/pull/175
