### ISSUE TITLE
If the user loses connectivity during on-boarding, they simply see a spinner

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#178]
If the user doesn't have connectivity, they see a spinner during on-boarding at the moment when they should see the prompt to enable ENS.  

The user should be informed that they need to check their connectivity.

**Comment by AlanSl** [comment]
@ahurworth Is this iOS or Android? Can you please share a video so we can see the exact flow? 

On Android I don't see this and it seems to work for me: if I disconnect during onboarding I get an error notice saying I'm disconnected and should try again

**Comment by AlanSl** [comment]
<img width=320 src="https://user-images.githubusercontent.com/29628323/91746789-10b31080-ebb5-11ea-8519-c0ce6b450c54.jpg" />

**Comment by JohnAGill** [comment]
This has been addressed and will be in the next release

**Comment by ahurworth** [comment]
Confirmed as working on iOS now.  thanks.
