### ISSUE TITLE
Update Chart Titles to be Title Case

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#182]
Please kindly update the chart titles to be title case instead of sentence case.

Total Persons Tested
Percent Tested Positive
Total Tested Positive

**Comment by floridemai** [comment]
I've added a translation label to this. We'll probably get more of these and update the translations at once. cc @fahd-arshad

**Comment by floridemai** [comment]
@ahurworth This should now be fixed.

**Comment by ahurworth** [comment]
Confirmed for English, but not for Spanish.  I don't know enough Spanish to know what capitalization rules need to be observed, however.  @mboskin can you confirm?

**Comment by floridemai** [comment]
@ahurworth We're going to generate a new file to be sent to the translator that will include the capitalised version. Same for other languages. So if this is ok for English I think we're safe to close down the issue.

**Comment by mboskin** [comment]
I can confirm that the translators can attend to capitalizations. We are working on having them review the app itself if possible.

**Comment by floridemai** [comment]
Closing this in favour of https://github.com/project-vagabond/covid-green-app/issues/319
