### ISSUE TITLE
Update County Picker Values

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#183]
In both the Health Log symptom tracker, and the charts filter, please update the values in the County picker as follows:

Change "Kings" to be "Kings (Brooklyn)"
Add a 2nd value "Brooklyn (Kings)"
Change "New York" to "New York (Manhattan)"
Add a 2nd value "Manhattan (New York)"
Change "Richmond" to "Richmond (Staten Island)"
Add a 2nd value "Staten Island (Richmond)"

Residents of Brooklyn, Manhattan and Staten Island are likely to have high abandon rates if we assume they will intuitively pick Kings, New York, and Richmond respectively.

**Comment by fahd-arshad** [comment]
This change should also apply to the County Picker in the "NY COVID Data" tab. 

In both cases, the data sent back to the API should remain "Kings", "New York", and "Richmond" even if the user picks the more user-friendly variants, so that there are no issues with data collection and API responses.

**Comment by JohnAGill** [comment]
This has been completed and should be in the next release

**Comment by ahurworth** [comment]
Confirmed
