### ISSUE TITLE
Chart Legend Label Wrapping on SE iPhone: Reduce Line Height

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#184]
On the SE iPhone (1st gen - i am not sure about 2nd gen, but i would assume so), the 7-day average legend label wraps.  We should reduce the line height between the two words (see screenshot below):

![IMG_DF1741078FA1-1](https://user-images.githubusercontent.com/68069959/91780674-3694e100-ebc6-11ea-920d-55b1732cc5e4.jpeg)

**Comment by floridemai** [comment]
Next build should have this fixed.
