### ISSUE TITLE
Visual issue. Design of the card 'Learn how to keep others safe' inconsistent in the Health Log symptoms page

### ISSUE THREAD

**Issue by helloantoine** [covid-alert-ny/covid-green-app#185]
**Issue:** Design of the card 'Learn how to keep others safe' inconsistent in the Health Log symptoms page.
![Image from iOS](https://user-images.githubusercontent.com/16833643/91838651-bada7900-ec45-11ea-8d5f-0a774451dbf7.png)
**Steps to reproduce:**  Do a full Heath Check and you should arrive to the Symptoms Log
**Solution:** Use the same component as the 'Learn how to ..'  card in MY COVID Alerts tab

@ahurworth

**Comment by floridemai** [comment]
@helloantoine Should be fixed in the next release

**Comment by helloantoine** [comment]
Not fixed in this Built @floridemai

**Comment by helloantoine** [comment]
Not fixed in the 1.0.0.33.

**Comment by helloantoine** [comment]
![Screenshot 2020-09-08 at 21 14 33](https://user-images.githubusercontent.com/16833643/92523464-4f317680-f218-11ea-8656-6e4a13c1636c.png)

**Comment by helloantoine** [comment]
Sorry if it was not clear. The one on the left is correct as per Zeplin. The one on the right incorrect.

**Comment by ahurworth** [comment]
Looks fixed to me.  @helloantoine ?

**Comment by helloantoine** [comment]
Some but not all unfortunately. Font size seems off.
![Screenshot 2020-09-14 at 19 17 27](https://user-images.githubusercontent.com/16833643/93128611-aa0b1800-f6c7-11ea-8472-0334552d1a8f.png)

**Comment by JohnAGill** [comment]
This has been changed and should be in the next build

**Comment by helloantoine** [comment]
Excellent. Thanks for caring.
