### ISSUE TITLE
Cosmetic. Thickness of white outline in the graph

### ISSUE THREAD

**Issue by helloantoine** [covid-alert-ny/covid-green-app#186]
Issue: 
![Image from iOS (1)](https://user-images.githubusercontent.com/16833643/91844244-fe85b080-ec4e-11ea-8017-2452ea35f903.png)

Solution: Make the white stroke thinner (below the brown stroke). If it's 5px thick, make it 3px.
![Screenshot 2020-09-01 at 12 31 27](https://user-images.githubusercontent.com/16833643/91844311-21b06000-ec4f-11ea-9d4d-5191e4e48e6a.png)

**Comment by JohnAGill** [comment]
This has been fixed and will be in the next build

**Comment by helloantoine** [comment]
Looks good to me. Thank you.
