### ISSUE TITLE
Feature. Split settings and add a link to 'Learn how the apps works' 

### ISSUE THREAD

**Issue by helloantoine** [covid-alert-ny/covid-green-app#199]
**Design:** 
[(https://nearform.invisionapp.com/share/NZY402QAG3Q#/428298602_settings)](https://nearform.invisionapp.com/share/NZY402QAG3Q#/428298602_settings)

**Link opens up:** [https://nearform.invisionapp.com/share/NZY402QAG3Q#/428105724_how-It-Works-1](https://nearform.invisionapp.com/share/NZY402QAG3Q#/428105724_how-It-Works-1)

@ahurworth

**Comment by AlanSl** [comment]
Done in https://github.com/project-vagabond/covid-green-app/pull/213, should be fixed in next build

**Comment by ahurworth** [comment]
confirmed.
