### ISSUE TITLE
Cosmetic. Tiny copy tweaks

### ISSUE THREAD

**Issue by helloantoine** [covid-alert-ny/covid-green-app#201]
**Before/After**

Get started **BECOMES** Get Started
How it works **BECOMES** How It works
If there’s a match, the app displays a COVID Alert. **BECOMES** If there’s a match, the app will display a COVID Alert.
You can change your mind at any time by going to App Settings **BECOMES** You can change your mind at any time by going to App Settings.
Yes I'd like to start my log **BECOMES** Yes, I’d Like to Start My Log
Your symptoms data helps them understand how COVID-19 is affecting NY. **BECOMES** Your symptoms data helps them understand COVID-19 and how it’s affecting NY.
All responses are optional. They will only be used anonymously for public health analysis. **BECOMES** All responses are optional and anonymous. The info is used only for public health analysis. 
I am feeling well today **BECOMES** I'm feeling well
Nausea or Vomiting **BECOMES** Nausea or vomiting
Your settings will be visible here as soon as you do your first log. **BECOMES** Basic details you provide about yourself, such as your age and gender, can be changed here after you make your first log entry.
Separate yourself **BECOMES** Separate yourself.
Stay in a room that is not shared **BECOMES** Stay in a room that's not shared
If not possible, clean and disinfect all surfaces after each use. **BECOMES** If you must share one, clean and disinfect all surfaces after each use.
Throw away used tissues. Bag your trash and leave outside your door. (No special handling is needed) **BECOMES** Throw away used tissues. Bag your trash and leave it outside your door. (No special handling is needed.)
Wash your hands often **BECOMES** Wash your hands often. **//ADD BREAKLINE**
with soap and water for 20 seconds each time, or if unavailable, use hand sanitizer with at least 60% alcohol. Use paper towels instead of shared towels **BECOMES** Wash with soap and water for 20 seconds. If that’s not possible, use hand sanitizer with at least 60% alcohol. Dry with paper towels instead of shared towels.
Talk to your Healthcare provider **BECOMES** Talk to your healthcare provider
call NYS Health Hotline **BECOMES** Call NYS Health Hotline 
If You test positive for COVID-19 **BECOMES** If You Test Positive for COVID-19
Share your close contact codes **BECOMES** Share Your Close Contact Codes

@floridemai @ahurworth

**Comment by helloantoine** [comment]
For visual reference.
[COVID copy fixes - 8_31.pdf](https://github.com/project-vagabond/covid-green-app/files/5157777/COVID.copy.fixes.-.8_31.pdf)

**Comment by ckiss** [comment]
fixed, avail in next build

**Comment by helloantoine** [comment]
Checked 4 of them. Looks good to me.
