### ISSUE TITLE
Translation issue. NY COVID Data tab.

### ISSUE THREAD

**Issue by helloantoine** [covid-alert-ny/covid-green-app#206]
**Device:** Lenovo P2, Android 9
**Issue:** Probably a copy/paste issue. The field underlined never gets translated. 
**Steps to reproduce** Go to NY COVID tab with language settings set to any language except the 5th one.
![Screenshot 2020-09-02 at 10 51 01](https://user-images.githubusercontent.com/16833643/91966955-78c73b00-ed0a-11ea-9024-5e59e37e0b46.png)

![Screenshot_20200902-105352_Pixel_Launcher](https://user-images.githubusercontent.com/16833643/91967109-a9a77000-ed0a-11ea-9cf3-f103377d3444.png)

**Comment by AlanSl** [comment]
Done in https://github.com/project-vagabond/covid-green-app/pull/214, should be fixed in next build

**Comment by helloantoine** [comment]
Great job. Looks good.
