### ISSUE TITLE
Language option in settings crashes the app on iOS

### ISSUE THREAD

**Issue by helloantoine** [covid-alert-ny/covid-green-app#207]
**Device** iPhone SE2
**Issue:** App crashes
**Steps to reproduce** Go to Settings > Languages

**Comment by helloantoine** [comment]
This is fixed in latest release. Happy to move to done. @ShaunBaker @floridemai

**Comment by floridemai** [comment]
@helloantoine That's strange as it seems nothing has been done to address it...

**Comment by helloantoine** [comment]
:crystal_ball:  Great job. Looks good.
