### ISSUE TITLE
Visual issue. Call 911 card not responsive when text is longer. 

### ISSUE THREAD

**Issue by helloantoine** [covid-alert-ny/covid-green-app#208]
**Issue:** Text doesn't wrap properly and conflicts with the arrow.
**Solution:** Reduce width of the block text
![Screenshot_20200902-115916_COVID_Alert_NY](https://user-images.githubusercontent.com/16833643/91973508-48849a00-ed14-11ea-9473-0a22682ba142.png)
![Screenshot_20200902-120220_COVID_Alert_NY](https://user-images.githubusercontent.com/16833643/91973518-4ae6f400-ed14-11ea-9970-d986b4edfef5.png)

**Comment by floridemai** [comment]
Fixed. Should be available in the next build.

**Comment by helloantoine** [comment]
:crystal_ball: Great job. Looks good.
