### ISSUE TITLE
Visual issue. Markdown formatting not interpreted

### ISSUE THREAD

**Issue by helloantoine** [covid-alert-ny/covid-green-app#209]
Issue: ** not interpreted as bold in languages other than English, in the **Learn how to keep other safe** page
Solution: Fix it! :)
![Screenshot 2020-09-02 at 12 05 16](https://user-images.githubusercontent.com/16833643/91973774-b5982f80-ed14-11ea-9782-ed071d0a9afa.png)

**Comment by ShaunBaker** [comment]
@helloantoine this is a text content issue - not a code issue.

Putting this on hold pending final translations - to verify those are indeed formatted correctly

**Comment by helloantoine** [comment]
Looks good to me
