### ISSUE TITLE
Cosmetic Issue. Background of the app slightly off

### ISSUE THREAD

**Issue by helloantoine** [covid-alert-ny/covid-green-app#211]
**Issue** It seems the background of the app is neutral gray instead of tinted gray.
**Solution** Make sure background of the app is: #F3F3F8
![Screenshot 2020-09-02 at 12 29 38](https://user-images.githubusercontent.com/16833643/91975874-fd6c8600-ed17-11ea-89de-920a771105dd.png)

**Comment by ckiss** [comment]
fixed, avail in next build

**Comment by helloantoine** [comment]
Perfect
