### ISSUE TITLE
Visual issue. Cards styling is off

### ISSUE THREAD

**Issue by helloantoine** [covid-alert-ny/covid-green-app#212]
**Issue:** Styling of the cards is off across the app. 
**Solution:** Make sure height of the card, padding and arrow size are correct. https://zpl.io/bWOzkyk

![Screenshot 2020-09-02 at 12 31 51](https://user-images.githubusercontent.com/16833643/91976038-49b7c600-ed18-11ea-8dc2-88178200f15c.png)

**Comment by ckiss** [comment]
fixed, avail in next build

**Comment by helloantoine** [comment]
Great work.  Merci
