### ISSUE TITLE
Cosmetic issue. Incorrect styling for warnings

### ISSUE THREAD

**Issue by helloantoine** [covid-alert-ny/covid-green-app#219]
**Issue:** Incorrect styling for warnings
**Solutions** Make sure to use #DC0000 across the app for the warning color. 
https://zpl.io/VOORYNl

![Screenshot 2020-09-02 at 14 52 04](https://user-images.githubusercontent.com/16833643/91992425-09624300-ed2c-11ea-9325-794a7d164eba.png)

**Comment by JohnAGill** [comment]
This has been completed and should be in the next release

**Comment by helloantoine** [comment]
I cannot see it in Today's Built. Still old style.

**Comment by floridemai** [comment]
@JohnAGill Can you check what happened here? Re-apply the fix if that's the case.

**Comment by fahd-arshad** [comment]
Bumping back to In Progress based on @helloantoine's comment above.

**Comment by floridemai** [comment]
@fahd-arshad Comment is from 8 of Sep. This should be fixed now. Can you validate @helloantoine

**Comment by helloantoine** [comment]
Perfect @floridemai . Thank you.
