### ISSUE TITLE
Step indicator is not in the reading order [Android]

### ISSUE THREAD

**Issue by jonnyjames** [covid-alert-ny/covid-green-app#220]
The step indicator found on the “How it works” screens is not included in the reading order. The visual information it provides is not available to TalkBack users. I would suggest including it in the reading order and providing a proper text alternative (e.g., “Step 2 of 4”).

![how-it-works - pagination controls](https://user-images.githubusercontent.com/7034772/91992747-7eb91e00-ed02-11ea-9f34-89597df8d72d.png)

Severity: Low

**Comment by floridemai** [comment]
@jonnyjames This has now been addressed. See https://github.com/project-vagabond/covid-green-app/issues/195

**Comment by jonnyjames** [comment]
@floridemai The pagination control is now in the reading order, but it has some extraneous label text, announced as "page selector, page 1 of 4, see[?] control". I would parse the text to include just "page 1 of 4" and remove the reference to "page selector' and "see[?] control", since it isn't a selectork and isn't actionable.

**Comment by floridemai** [comment]
@jonnyjames Done.

**Comment by jonnyjames** [comment]
This is now fixed. Closing this issue.
