### ISSUE TITLE
Usability. Incorrect voiceover on the share icon

### ISSUE THREAD

**Issue by helloantoine** [covid-alert-ny/covid-green-app#222]
**Issue:** Incorrect voiceover on the share icon 
**Solution:** 
It says: "View or amend application settings, possibly share"
It should say: "Share application with someone"
![Image from iOS (3)](https://user-images.githubusercontent.com/16833643/91992852-87bee500-ed2c-11ea-94ef-ac635a159d3b.png)

@ahurworth

**Comment by floridemai** [comment]
@helloantoine This has now been addressed. See https://github.com/project-vagabond/covid-green-app/issues/216

**Comment by helloantoine** [comment]
Tested. Works well. Good job Paul.
