### ISSUE TITLE
Cosmetic issue. Cropped text in text fields when font size of device a bit larger

### ISSUE THREAD

**Issue by helloantoine** [covid-alert-ny/covid-green-app#227]
Issue: Text is cropped
Where: My COVID Alerts > What to do if... > Share your Close Contact Codes
Solution: Fix it. 

![image_from_ios](https://user-images.githubusercontent.com/16833643/91998508-3534f700-ed33-11ea-9917-0a6e9ad6b234.png)

@ahurworth

**Comment by floridemai** [comment]
@helloantoine This has now been addressed.

**Comment by helloantoine** [comment]
Looking good.
