### ISSUE TITLE
Content. Delete my data. Content should be different for iOS and Android 

### ISSUE THREAD

**Issue by helloantoine** [covid-alert-ny/covid-green-app#228]
**Where:** App Settings > Delete my data
**Issue:** Content was designed to be specific for Android or iOS. Not implemented as such.
**Solution:** 
iOS content is: 
https://nearform.invisionapp.com/share/NZY402QAG3Q#/428733342_settings-Leave-IOS

Android content is: 
https://nearform.invisionapp.com/share/NZY402QAG3Q#/428733343_settings-Leave-Android

**Only the last paragraph changes:**
//iOS
To delete the random codes, you must go to your phone’s Settings and search for “Exposure Logging”.  Then, select “COVID-19 Exposure Logging” and tap on the “Delete Exposure Log” button. To stop storing new codes, you should turn off “Exposure Logging”.

//Android
To delete the random codes, go to your phone’s Settings and select “Google Services & Preferences.” Then, select “COVID-19 Exposure Notifications” and tap the “Delete Random IDs” button. To stop storing new codes, you should turn off “Use Exposure Notifications.”

@ahurworth

**Comment by JohnAGill** [comment]
This has been addressed and will be in the next build

**Comment by helloantoine** [comment]
Excellent. Looks good.
