### ISSUE TITLE
Tabbed navigation interface doesn't convey role/state [Android]

### ISSUE THREAD

**Issue by jonnyjames** [covid-alert-ny/covid-green-app#229]
For the tabbed navigation interface at the bottom of the **health intro** screens, the tabs are **not** marked up as buttonsm, and the 'selected" state for the tabs isn't conveyed to TalkBack users. TalkBack users may not understand which button (tab) is currently selected.

![health intro - tabbed interface selected button](https://user-images.githubusercontent.com/7034772/92000286-5d106480-ed0b-11ea-8525-1b49d8f6eaa2.png)

Severity: High

**Comment by floridemai** [comment]
@jonnyjames This has now been addressed.

**Comment by jonnyjames** [comment]
I can confirm this has been fixed. Closing this issue.
