### ISSUE TITLE
[DESIGN ONLY] Graph improvement 

### ISSUE THREAD

**Issue by helloantoine** [covid-alert-ny/covid-green-app#233]
Requirement: On the data tab, time series graph are lacking having the **Latest value**.  Need exploration adding it. 

@ahurworth @fahd-arshad

**Comment by ahurworth** [comment]
I think the main idea to communicate is: are things getting better or worse?  The absolute number is interesting, but not meaningful to most people in isolation.
I'd like to see the number alongside the % change, and something we can apply to each of the charts.

**Comment by helloantoine** [comment]
First pass. @fahd-arshad @ahurworth 

So the idea would be to have 30 days x-axis. (current data coming from backend is 29 days).
Mark the first, lat and middle times. Properly centre the text under the related bar + add a little vertical bar.
![Screenshot 2020-09-03 at 18 00 28](https://user-images.githubusercontent.com/16833643/92144975-6b47a900-ee0f-11ea-927c-2b92cdda3e28.png)

**Comment by helloantoine** [comment]
@ahurworth @fahd-arshad 
**Many experiments. These are the last 2 winners we have at the moment.**
Option A: Only the latest value. Includes both the daily figure AND the average. 
> Makes the page longer but each graph still fits nicely in a screen. 

Option B: Interactive graph. User can tap to see the value. We do not display the average. 
> Could be tricky for people to 'hit' the bar and we'll need to think of potential accessibility issues. screen reader experience... 

**Both include:**
> Readjustment and cleanup of bars and X-Axis labels
> Legend for daily figure slightly less big

I played with the colors to reflect positive or negative trend. Issue is that line going up for number of test is positive BUT line going down for the % positive cases is also positive. Could be confusing for people.

![option A](https://user-images.githubusercontent.com/16833643/92263547-b5469280-eed4-11ea-8afa-7a9f8098323b.png)
![option B](https://user-images.githubusercontent.com/16833643/92263552-b7105600-eed4-11ea-9266-5694f0cd7b63.png)

**Comment by ahurworth** [comment]
Thanks @helloantoine.  I like the overall direction.  I wonder if we might dial back the overall visual weight of the number.  The black fill and font size being similar (if not the same) as the chart title feels like those elements are competing.  Could something along these lines work?  (Note: i'm exploring adding back in the % change - what do you think?)

![image](https://user-images.githubusercontent.com/68069959/92279879-3c403e80-eec6-11ea-8ea6-95ec63af5676.png)

**Comment by helloantoine** [comment]
> Thanks @helloantoine. I like the overall direction. I wonder if we might dial back the overall visual weight of the number. The black fill and font size being similar (if not the same) as the chart title feels like those elements are competing. Could something along these lines work? (Note: i'm exploring adding back in the % change - what do you think?)
> 
> ![image](https://user-images.githubusercontent.com/68069959/92279879-3c403e80-eec6-11ea-8ea6-95ec63af5676.png)

Looks clean. 

The number on the graph (99,999) is very much faded in the graph, by design. I'm just wondering if we could kill it altogether? As an anecdote, I personally check this number on the Irish app to see if Kilkenny has more cases and how many? But I could easily figure it out from looking at the scale. However, I'm wondering if reading the day wouldn't be the challenge here? Not for the latest date, but rather for a date in the middle. I would suggest we 'park' the interactivity for now, either keep the latest value (like you did), either kill it until we bring interactivity.

**Comment by ahurworth** [comment]
Circling back to the original request, it was to add the most recent figure.  Personally I think it's hard to find out the exact figure from the chart without this.  But, my POV is that actually it's the % change that people will find more meaningful; the most recent absolute figure it's as helpful without the context of prior days' data.  I agree though that we could park the interactivity for now.
@fahd-arshad Can you weigh in here on what we ought to do with Shawn's request?  We have a number of design permutations depending on how you respond, and I'd like to get it over to Mahesh for final OK so that Eng can implement.

**Comment by fahd-arshad** [comment]
IMHO the sharktooth callout does its job. For the given chart, it shows the
latest value. I agree the %age is an important value, but if this pattern
applies to each chart, one of the charts is the %age one. I suggest we
simply lead with that chart instead of trying to put in the %age value in
the raw # tested chart.

**Comment by helloantoine** [comment]
Updated:
![data tab](https://user-images.githubusercontent.com/16833643/92494341-82124500-f1ed-11ea-8c90-42c55c8e9b94.png)

**Comment by ahurworth** [comment]
Thanks Antoine.  @fahd-arshad I will send this version to Mahesh for his confirmation.  In the meantime Antoine is creating the issue.
