### ISSUE TITLE
Tabbed navigation interface doesn’t convey role/state [iOS]

### ISSUE THREAD

**Issue by willslone** [covid-alert-ny/covid-green-app#234]
The tabbed navigation items are announced without any role information and the selected tab does not convey its selected state to VoiceOver users. For example, the “My Health Log” tab control is simply announced as “My Health Log” by VoiceOver.

![“My Health Log” tab control focus with VoiceOver and announced as “My Health Log”](https://user-images.githubusercontent.com/4437084/92018046-a02a0200-ed22-11ea-84e8-a59b33ec5fe4.png)

Use the accessibilityRole property to give the tabbed navigation container a role of tablist and each control a role of tab. The accessibilityState property can be used to convey the selected state of the currently selected tab to VoiceOver users. To emulate the way iOS tab controls are announced with position information (e.g., “2 of 4”), I suggest including that information in the accessibilityLabel of each control.

```javascript
<View accessibilityRole='tablist'>
  <TouchableOpacity
    onPress={…}
    accessibilityLabel='NY COVID Data, 1 of 4'
    accessibilityRole='tab'
    accessibilityState={{selected: false}}
  >
    <Image source={…} />
    <Text>NY COVID DATA</Text>
  </TouchableOpacity>
  <TouchableOpacity
    onPress={…}
    accessibilityLabel='My Health Log, 2 of 4'
    accessibilityRole='tab'
    accessibilityState={{selected: true}}
  >
    <Image source={…} />
    <Text>My Health Log</Text>
  </TouchableOpacity>
  <TouchableOpacity
    onPress={…}
    accessibilityLabel='My COVID Alerts, 3 of 4'
    accessibilityRole='tab'
    accessibilityState={{selected: false}}
  >
    <Image source={…} />
    <Text>My Health Log</Text>
  </TouchableOpacity>
  <TouchableOpacity
    onPress={…}
    accessibilityLabel='App Settings!, 4 of 4'
    accessibilityRole='tab'
    accessibilityState={{selected: false}}
  >
    <Image source={…} />
    <Text>My Health Log</Text>
  </TouchableOpacity>
</View>
```

**Comment by willslone** [comment]
Retested and the issue has been resolved with the exception of the last “App” tab.

**Comment by floridemai** [comment]
@willslone I've tested again on my device and it works. The tabbed navigation is part of a loop so if the first three works should happen to the last tab. Can you check this one again please? Thanks

**Comment by willslone** [comment]
I just tested the App tab again and the selected state is announced, but not role and position information.

![App tab control focused by VoiceOver and announced as “selected, App”](https://user-images.githubusercontent.com/4437084/92267398-a220cc00-eeae-11ea-8555-cb977d7bdcfc.png)

**Comment by floridemai** [comment]
@willslone Is this android as it works on my iPhone XS. It might be due to the fact that the label is "App\nSettings", which is the text displayed. Should we create a label for a11y without the \n? We do have it in quite a few places I'll have to check the others as well.

**Comment by willslone** [comment]
@floridemai I’m testing on iOS (iPhone SE). I’m not sure if including “\n” is causing the issue, but I would leave it out of the a11y label and then test with VoiceOver to see if it makes a difference.

**Comment by floridemai** [comment]
<img src="https://user-images.githubusercontent.com/1158133/92272855-036a8e80-eef3-11ea-95e4-adb823879d0b.PNG" width="400">
<img src="https://user-images.githubusercontent.com/1158133/92272857-049bbb80-eef3-11ea-8e07-f2f00fa6dcc6.PNG" width="400">

The VoiceOver does say all the text it's only the caption that is not shown due to the new line. iPhone XS 13.6.1

**Comment by willslone** [comment]
@floridemai I see. My bad for relying on the caption. Sorry about that.
