### ISSUE TITLE
"Share Your Close Contact Codes" entries are clipped [Android]

### ISSUE THREAD

**Issue by jonnyjames** [covid-alert-ny/covid-green-app#235]
The user "Close Contact Code" entries are clipped for sighted users, when the Android device font size is set to "Largest" (Accessibility > Font size) which may increase the likelihood of errors.

![share IDs Pre-Entry - form - clipped entries](https://user-images.githubusercontent.com/7034772/92019666-fbf58a80-ed24-11ea-9cd9-e281e4b5cb3e.png)

**Comment by floridemai** [comment]
@jonnyjames This has now been addressed.

**Comment by jonnyjames** [comment]
@floridemai This issue is confirmed fixed. Closing this issue.
