### ISSUE TITLE
Radio buttons in overlays do not convey their role/state [iOS]

### ISSUE THREAD

**Issue by willslone** [covid-alert-ny/covid-green-app#243]
The form controls that behave as radio buttons (only one option selected at a time) in the “Select your county”, “Gender identity”, “Age range”, “Race”, and “Ethnicity” overlays do not convey a role of radio or their selected state to VoiceOver users

![“0-17” radio button focused by VoiceOver and announced as “0-17”](https://user-images.githubusercontent.com/4437084/92033946-84325a80-ed3a-11ea-987a-d059fc01a31a.png)

Use the accessibilityRole attribute to give the form group container a role of radiogroup and each radio button a role of radio. Use the accessibilityState attribute to convey the selected state of the currently selected button. 

```javascript
<View accessibilityRole='radiogroup'>
  <TouchableOpacity
    onPress={…}
    accessibilityRole='radio'
    accessibilityState={{selected: true}}
  >
    <Text>0-17</Text>
  </TouchableOpacity>
  <TouchableOpacity
    onPress={…}
    accessibilityRole='radio'
    accessibilityState={{selected: false}}
  >
    <Text>18-34</Text>
  </TouchableOpacity>
  {/* Rest of options */}
</View>
```

**Comment by floridemai** [comment]
@willslone This has now been addressed. Thanks for the suggestion ;)
