### ISSUE TITLE
White screen observed on tapping on App Settings on iPhone 11 Pro Max iOS 13.6

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#247]
Repro steps:

Update via testflight to build v25
tap on Settings -> white screen, can't do anything but kill the app

Per @dharding this is as a result of the debug menu being active.

**Comment by floridemai** [comment]
@ahurworth Should be fixed in build 26

**Comment by ahurworth** [comment]
Resolved thanks Paul!
