### ISSUE TITLE
Application number in App Settings should be at the bottom of the screen; content should not scroll under it

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#249]
See screenshot from iPhone SE:
The last two items in the table scroll under the application number, make it feel like there is a visual bug, and covers the need to scroll in one remaining row in the table.  The user needs to scroll to reveal a remaining row in the table.

![IMG_0016](https://user-images.githubusercontent.com/68069959/92039630-60bfdd80-ed43-11ea-8dc3-082e2f476515.PNG)

**Comment by AlanSl** [comment]
Done in https://github.com/project-vagabond/covid-green-app/pull/283 should be fixed in next build
