### ISSUE TITLE
Checkin card: Remove the logic of returning day (UX change from COVID green)

### ISSUE THREAD

**Issue by antoineaware** [covid-alert-ny/covid-green-app#25]
In the NY app, we won't keep the logic of changing the card in the NY COVID Data tab about the Health Log.
Card will be the same on day 1, 2,...

See screenshot:
![2020-08-14 at 12 16 31](https://user-images.githubusercontent.com/5053066/90244166-1f18d280-de28-11ea-85fd-60c69dafcde8.png)

**Comment by fahd-arshad** [comment]
@antoineaware Testing mentions. I'm not sure why you aren't able to mention me. My username does have a - between my first and last names.

**Comment by fahd-arshad** [comment]
@ShaunBaker testing only. Pls ignore.

**Comment by floridemai** [comment]
> ShaunBaker moved this from Backlog to QA Review in Launch 9 days ago.

Also the old card do not exist in the code (i've removed them in another PR). Closing this one.
