### ISSUE TITLE
Visual issue: Purple rubber band effect seen on first screen of on-boarding.

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#251]
Purple rubber band effect seen on first screen of on-boarding.  Compare with screen 2.  See screen-recording, attached)

[IMG_0017.TRIM.MOV.zip](https://github.com/project-vagabond/covid-green-app/files/5164976/IMG_0017.TRIM.MOV.zip)

**Comment by floridemai** [comment]
@ahurworth Should be addressed in the next build.
