### ISSUE TITLE
Visual bug: Chart date labels - uneven spacing

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#255]
Last two dates labels are much closer together than the others (see 26 Aug and 30 Aug bars on the chart).  This creates a visual imbalance on all charts, and a clash on iPhone SE.

Screenshot from iPhone 11 Pro Max:

![IMG_5B2D5B7FDA63-1](https://user-images.githubusercontent.com/68069959/92041559-72ef4b00-ed46-11ea-9317-9e22644d9456.jpeg)

Screenshot from SE:

![IMG_0019](https://user-images.githubusercontent.com/68069959/92041421-31f73680-ed46-11ea-9d7c-c74c3ca37fc7.PNG)

**Comment by floridemai** [comment]
@ahurworth This has been addressed with a temporary fix. We're going to have new designs for charts so it should be fine until that point.
