### ISSUE TITLE
Link not identified as a link [iOS]

### ISSUE THREAD

**Issue by willslone** [covid-alert-ny/covid-green-app#265]
The “Find a site near you” link on the My Health Log Results C (“Not feeling well”) screen is not conveyed to VoiceOver users as a link.

![](https://user-images.githubusercontent.com/4437084/92048801-af2aa780-ed56-11ea-9855-2f2f5e4bc394.png)

Use the accessibilityRole attribute on the interactive element (TouchableOpacity, Pressable, etc.) to convey a link role to VoiceOver users.

```javascript
<TouchableOpacity onPress={…} accessibilityRole='link'>
  <Text>Find a site near you</Text>
</TouchableOpacity>
```

**Comment by floridemai** [comment]
@willslone Can you check in the next build please. Thanks

**Comment by helloantoine** [comment]
Looks good.
