### ISSUE TITLE
Error message is not immediately apparent to VoiceOver users [iOS]

### ISSUE THREAD

**Issue by willslone** [covid-alert-ny/covid-green-app#268]
Upon entering an invalid code on the Share Your Close Contact Codes screen, the “Invalid code. Please try again.” message is shown below the text fields. It is not immediately apparent to VoiceOver users that the data they entered is invalid.

![](https://user-images.githubusercontent.com/4437084/92055280-4ba37880-ed5c-11ea-8a79-6f985253c429.png)

Ideally the message could be announced upon its appearance without moving the users focus, but I’m not aware of a way to do that with React Native and iOS (there is a way for Android) without resorting to Native Modules. I would suggest programmatically associating the error message (i.e., appending the error message to the accessibilityLabel of the text field) with the first text field in the group (only when the message is actually displayed) and moving focus to said field when the message displays.

**Comment by JohnAGill** [comment]
This will be in the next build
