### ISSUE TITLE
Exposure contact notification on iOS does not tap into My COVID Alerts screen

### ISSUE THREAD

**Issue by dharding** [covid-alert-ny/covid-green-app#271]
On iOS with build 1.0.0.26 I was able to get an exposure notification. When I tapped on this notification, it launched the app, but it did not take me to the "My COVID Alerts" screen or the alerts details screen. It simply foregrounded the app in the state I left it.

**Comment by davidjharding** [comment]
Note, this may also be an issue on Android.

**Comment by floridemai** [comment]
@dharding This has been now addressed.

**Comment by helloantoine** [comment]
Looks good to me now.
