### ISSUE TITLE
Date format has leading zero on exposure alert detail screen

### ISSUE THREAD

**Issue by dharding** [covid-alert-ny/covid-green-app#273]
The day has a leading zero. It should not.

![File (2)](https://user-images.githubusercontent.com/8274/92059778-1bf66f80-ed60-11ea-8e1a-e591ab5f3fa7.jpg)

**Comment by floridemai** [comment]
Should be fixed in the next build

**Comment by helloantoine** [comment]
Looks good to me. Thank you!
