### ISSUE TITLE
Date of contact is off by a day in an exposure alert

### ISSUE THREAD

**Issue by dharding** [covid-alert-ny/covid-green-app#274]
This alert is telling me that the contact was on the 1st of September but I entered a diagnosis code on the 2nd of September and had the phones in contact with each other on the 2nd.

![File (2)](https://user-images.githubusercontent.com/8274/92059887-64ae2880-ed60-11ea-9cd1-8de51b7de763.jpg)

**Comment by colmharte** [comment]
When you upload you are uploading keys from yesterday and back, not todays key. So above is as expected.

**Comment by colmharte** [comment]
Can we close this?
