### ISSUE TITLE
Clipped text at larger font sizes [iOS]

### ISSUE THREAD

**Issue by willslone** [covid-alert-ny/covid-green-app#276]
There are a few instances where text is clipped or completely obscured when viewing the screens at larger text sizes (turned on via the iOS accessibility settings). The screenshots below were taken at the maximum text size (i.e., AX5), but some of the issues also occur at smaller sizes (i.e., AX3, which is still much larger than default).

![](https://user-images.githubusercontent.com/4437084/92061890-63332f00-ed65-11ea-8ffd-2104a30982cb.PNG)
![](https://user-images.githubusercontent.com/4437084/92061894-63cbc580-ed65-11ea-8d12-f24db4d3dcb9.PNG)
![](https://user-images.githubusercontent.com/4437084/92061896-63cbc580-ed65-11ea-9850-50f782df21f8.PNG)
![](https://user-images.githubusercontent.com/4437084/92061897-64645c00-ed65-11ea-8a3f-5f5918f580bf.PNG)

**Comment by JohnAGill** [comment]
This will be in the next build

**Comment by willslone** [comment]
A couple of the issues from the screens have been resolved, but others persist.

FYI, I am testing on an iPhone SE (i.e., the iPhone with the smallest screen / lowest resolution). Some of the issues may not occur on larger devices.

I noticed on the How it Works screen that the previous, next, and close buttons either don’t increase or increase only slightly in size when the larger text size settings are applied. This may prevent the text from becoming clipped or obscured, but it defeats the purpose of letting users increase the text to a size where they can view it comfortably. Text must respond appropriately to an increase in size via the iOS accessibility settings.

**Comment by helloantoine** [comment]
Agree Will. We know capping the text is a hack but unfortunately, the effort to make every text fully dynamic is very high. Probably a task that will need to be tackled separately after the launch. 

I noticed everything is working on my iPhone SE except the How it works title in the overlay. @JohnAGill

**Comment by JohnAGill** [comment]
This should now be fixed and in the next build
