### ISSUE TITLE
Visual Bug: Learn how to keep others safe style

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#279]
Learn how to keep others safe button style isn't correct on the "If you test positive" drill in screen.  @helloantoine Can you advise if it's using regular and needs bold or heavy?

![Screenshot_20200902-222706](https://user-images.githubusercontent.com/68069959/92064552-b01a0400-ed6b-11ea-8841-83a49eac5646.png)

**Comment by floridemai** [comment]
@helloantoine ?

**Comment by helloantoine** [comment]
Styling of the cards should be consistent across the app. Follow this:
https://zpl.io/adOgjk5

**Comment by ckiss** [comment]
fixed, avail in next build
