### ISSUE TITLE
Visual bug: Share your Close Contact Codes button has incorrect colored drop shadow

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#280]
@helloantoine to advise correct hex value.  The drop shadow is currently showing as black.

![Screenshot_20200902-222706](https://user-images.githubusercontent.com/68069959/92064683-f7a09000-ed6b-11ea-8bdb-08bb120049db.png)

**Comment by floridemai** [comment]
@helloantoine ?

**Comment by ckiss** [comment]
fix, avail in next release
