### ISSUE TITLE
"Share App Usage" label and switch control are not programmatically associated [Android]

### ISSUE THREAD

**Issue by jonnyjames** [covid-alert-ny/covid-green-app#282]
The "Share App Usage" label is announced separately from the switch control. TalkBack announces the switch control as "switch, on"

![settings-App-Usage - Label - Switch control](https://user-images.githubusercontent.com/7034772/92067524-89ab9700-ed72-11ea-96ed-27323a87ea63.png)

**Remediation Guidance:**
Programmatically associate the label by including it in the accessibilityLabel attribute on the switch. Hide the visible text label from VoiceOver users via the accessibilityElementsHidden attribute, as not to announce the label twice to said users.
```javascript
<View accessibilityElementsHidden={true}>
  <Text>Share App Usage</Text>
</View>
<Switch accessibilityLabel='Share App Usage' />
```

**Comment by floridemai** [comment]
@jonnyjames This has now been addressed.

**Comment by jonnyjames** [comment]
@floridemai I am confirming this issue is fixed. Closing this issue.
