### ISSUE TITLE
Focus management after submitting a valid contact code [iOS]

### ISSUE THREAD

**Issue by willslone** [covid-alert-ny/covid-green-app#293]
Upon submitting a valid contact code on the Share Your Close Contact Codes screen, new instructional text appears below the text fields, but focus is moved to the top of the screen.

I would suggest moving focus to the new instructional text, as it is not immediately apparent to VoiceOver users. Upon hearing the “COVID ALERT NY” announced after form submission, they may incorrectly assume they have been taken to a new screen.

**Comment by JohnAGill** [comment]
This will be in the next build
