### ISSUE TITLE
Error message is not immediately apparent to TalkBack users [Android]

### ISSUE THREAD

**Issue by jonnyjames** [covid-alert-ny/covid-green-app#306]
Upon entering an invalid code on the "Share Your Close Contact Codes" screen, the “Invalid code. Please try again.” message is shown below the text fields. It is not immediately apparent to TalkBack users that the data they entered is invalid.

![share IDs Pre-Entry - error msg](https://user-images.githubusercontent.com/7034772/92146908-66bbca00-ede8-11ea-9363-fe0eced5a51f.png)

Ensure the validation error message is announced upon its appearance without moving the users focus. We also suggest programmatically associating the error message (i.e., appending the error message to the `accessibilityLabel` of the text field) with the first text field in the group (only when the message is actually displayed) and moving focus to said field when the message displays.

**Comment by JohnAGill** [comment]
This will be in the next build

**Comment by jonnyjames** [comment]
This issue is now fixed. Closing this issue.
