### ISSUE TITLE
Button’s disabled state is not conveyed to TalkBack users [Android]

### ISSUE THREAD

**Issue by jonnyjames** [covid-alert-ny/covid-green-app#310]
After confirming changes on the **App Settings** -> **My Health Log** screen, the “Confirm changes” button becomes disabled. The disabled state is not conveyed to TalkBack users.

![settings - NRV - Disabled confirm changes button](https://user-images.githubusercontent.com/7034772/92152886-6e33a100-edf1-11ea-89fb-3c87be96d5b3.png)

The “Confirm changes” button on the **My Health Log Symptoms List** screen is disabled until a checkbox is checked, but the disabled state is not conveyed to TalkBack users.

![my Health Log - NRV - Disabled Confirm Changes btn](https://user-images.githubusercontent.com/7034772/92153045-a76c1100-edf1-11ea-9bf9-48e6c59f21aa.png)

**Remediation Guidance**

Use the `accessibilityState` attribute to convey the `disabled` state to TalkBack users.
```javascript
<TouchableOpacity
  onPress={…}
  accessibilityRole='button'
  accessibilityState={{disabled: true}}
>
  <Text>Confirm Changes</Text>
</TouchableOpacity>
```

**Comment by floridemai** [comment]
@jonnyjames Button state is now captured. After applying the changes the focus moves to the "Changes updated" alert. Moving to the button does highlight that it is ow disabled.

**Comment by jonnyjames** [comment]
@floridemai This issue is fixed. Closing this issue.
