### ISSUE TITLE
Buttons marked up as links [Android]

### ISSUE THREAD

**Issue by jonnyjames** [covid-alert-ny/covid-green-app#311]
The “You can read the Data and Privacy Policy here” button found on the **Help Improve This App** and **Delete My Data** screens are incorrectly conveyed to TalkBack users as links. The link role is only appropriate for interactive elements that open a webpage in Chrome.

**Help Improve This App screen**
![help-Improve-This-App - NRV - Button as link](https://user-images.githubusercontent.com/7034772/92154119-49402d80-edf3-11ea-9611-9013f172f582.png)

**Delete My Data screen**
![settings-Leave-Android - NRV - Button as link](https://user-images.githubusercontent.com/7034772/92153805-d20a9980-edf2-11ea-8d6a-83e83f086d5c.png)

**Remediation Guidance**
Use the `Button` role for these controls.

**Comment by floridemai** [comment]
@jonnyjames Hopefully this is fixed now.

**Comment by jonnyjames** [comment]
@floridemai Confirming this issue is fixed. Closing issue.
