### ISSUE TITLE
Screen should be titled "COVID Alert NY"

### ISSUE THREAD

**Issue by mboskin** [covid-alert-ny/covid-green-app#315]
Screen is incorrectly labeled "COVID SMART NY".  See attached.
![COVID Alert Screen 2020-09-03 145611](https://user-images.githubusercontent.com/70291664/92155750-ddab8f80-edf5-11ea-8022-473acd72e5b0.png)

Found by Tawfic, Bassem (ITS) at 2:51

**Comment by floridemai** [comment]
@mboskin This must be a very old version of the app. The above text not being present in the app anymore suggests that as well.

**Comment by mboskin** [comment]
OK. I will close the issue.

_____________________

[REDACTED}
*Removed e-mail signature as the e-mail reply feature was used*
