### ISSUE TITLE
Focus management when an overlay is triggered [Android]

### ISSUE THREAD

**Issue by jonnyjames** [covid-alert-ny/covid-green-app#316]
Upon triggering the “Gender identity”, “Age range”, “Race”, “Ethnicity” overlays, focus is moved to the overlay container, which is announced by TalkBack as "Choose...". 

![overlay-Choose-Age-Range - Focus - ovelay](https://user-images.githubusercontent.com/7034772/92163910-7516df80-ee02-11ea-9777-e6565acf73ce.png)

**Remediation Guidance**
We recommend moving focus to the form group label (e.g., “Choose your gender”) when the overlays are opened.

**Comment by floridemai** [comment]
@jonnyjames This is fixed now.

**Comment by helloantoine** [comment]
Side note. I do not see the tick as a blue bubble on my device. 
![screenshot_20200904-104938_covid_alert_ny](https://user-images.githubusercontent.com/16833643/92226457-b22fb000-ee9c-11ea-87b1-580dbf2cfa25.png)

**Comment by jonnyjames** [comment]
@floridemai I can confirm this issue is fixed. Closing issue.

**Comment by jonnyjames** [comment]
@floridemai The "Choose your gender identity" and "Choose your race" overlays still have focus move to the overlay container when triggered, not the overlays heading.

**Comment by floridemai** [comment]
@jonnyjames I've done some minor improvements here, but this an area we have to have a deeper look at (when all the major issue have been addressed)

**Comment by jonnyjames** [comment]
@floridemai It's at least consistent how, with focus moving to the overlay container and the overlays title/heading being announced. I am closing this issue.
