### ISSUE TITLE
Cosmetic. Health Log screen. Title top margin incorrect 

### ISSUE THREAD

**Issue by helloantoine** [covid-alert-ny/covid-green-app#324]
**Issue:** Top margin above the title is inconsistent with all the other pages' title.
**Solution** Apply the same margin as for all the other pages (example: NY COVID Data tab).
![Image from iOS (9)](https://user-images.githubusercontent.com/16833643/92245686-9fc56e80-eebc-11ea-820c-96726191b0dc.png)

**Comment by helloantoine** [comment]
This is still an issue for me @floridemai . 
![Image from iOS (6)](https://user-images.githubusercontent.com/16833643/92382814-253b5f80-f105-11ea-9317-f9f544baa85e.png)

**Comment by floridemai** [comment]
Will be available in the next build.

**Comment by helloantoine** [comment]
Perfect. thx
