### ISSUE TITLE
Cosmetic. Tab navigation warning state is missing 

### ISSUE THREAD

**Issue by helloantoine** [covid-alert-ny/covid-green-app#326]
Issue: Design of the warning state for the **My COVID Alerts** tab not implemented when the user receives an exposure alert.
Solution: Implement the **red alert** in the tab.
https://zpl.io/agA4rmA

@ahurworth

**Comment by ckiss** [comment]
fixed, avail in next build

**Comment by helloantoine** [comment]
Tabs are not styled properly. @ckiss .
![Screenshot 2020-09-07 at 12 43 49](https://user-images.githubusercontent.com/16833643/92506706-c0affb80-f1fd-11ea-922e-07705adb1c18.png)

**Comment by ckiss** [comment]
fixed, avail in next build.

Thanks @helloantoine for your input!

**Comment by fahd-arshad** [comment]
Hmmm. Now I see only the red caution triangle in iOS build 35, but as per the spec above looks like it should be the bell icon with the triangle almost as superscript. Leaving it to @helloantoine to confirm.

**Comment by helloantoine** [comment]
Hi Fahd.  I discussed this with Cristian and Alex as well. We're going with the single hazard sign. Simpler.
