### ISSUE TITLE
Bluetooth disabled should display yellow banner

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#333]
When Bluetooth is disabled, a yellow banner should be displayed on both the NY COVID Data tab.  It is currently not. @helloantoine can help with specs from Zeplin.

![image](https://user-images.githubusercontent.com/68069959/92287366-9695cb00-eed7-11ea-9464-114273102714.png)

**Comment by helloantoine** [comment]
https://zpl.io/a7M9Jgq

**Comment by floridemai** [comment]
@ahurworth This should be fix in build 34+.

**Comment by fahd-arshad** [comment]
I just confirmed this is working in build 35 on iOS.
