### ISSUE TITLE
Cosmetic. How it works. Inconsistent spacing between visual and text

### ISSUE THREAD

**Issue by helloantoine** [covid-alert-ny/covid-green-app#338]
![Screenshot 2020-09-06 at 11 19 03](https://user-images.githubusercontent.com/16833643/92323709-db824480-f032-11ea-9583-527160468ea2.png)

Issue: How it works. Inconsistent spacing between visual and text. Specifically between screen 2 and 3
Solution: Remove the spacing all together on the 4 screens.

**Comment by helloantoine** [comment]
![Screenshot 2020-09-06 at 11 24 30](https://user-images.githubusercontent.com/16833643/92323807-90b4fc80-f033-11ea-8f81-190cbb5fa9ac.png)

**Comment by floridemai** [comment]
@helloantoine Should be fixed in the next build

**Comment by helloantoine** [comment]
Great work.  Merci
