### ISSUE TITLE
[DESIGN ONLY] Explore Updates to the yellow banner in the event Bluetooth is not enabled

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#340]
Should the wording be more direct on the NY COVID Data tab, and specify "please turn on BT"?  Does it really need a drill in screen?

**Comment by helloantoine** [comment]
Yes, once the orange banner itself is implemented with a generic message we can think of more granular message. Keep in my app can only detect when bluetooth is changed in the settings, not the control center. This mean we have a fairly large description. 

We have more real estate in the COVID Alerts screen. I would be worried the visible part of the **NY Data** screen becomes things unrelated to data itself.

**Comment by helloantoine** [comment]
![Bluetooth granular msg](https://user-images.githubusercontent.com/16833643/92393883-7c96fb00-f118-11ea-8fd1-d90a394661f5.png)

**Comment by helloantoine** [comment]
Discussed with Paul. Created an issue for it with final designs:
https://github.com/project-vagabond/covid-green-app/issues/417
