### ISSUE TITLE
[DESIGN ONLY] Explore ways to make the on-boarding buttons locked at the bottom

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#342]
Some challenges: 
- Screen two, where there are three action buttons (primary, secondary and skip)
- iPhone SE where much of the screen may be chrome and not much content

**Comment by helloantoine** [comment]
Quick mockup of large screen size and small screen size. @ahurworth 
![Screenshot 2020-09-07 at 16 57 24](https://user-images.githubusercontent.com/16833643/92404356-431bbb00-f12b-11ea-80a1-a4d37eea3615.png)

**Comment by helloantoine** [comment]
I'll park this for now. I discussed with Paul and we now have a task to handle iPhone SE intro screen so it does not require a scroll by default.
https://github.com/project-vagabond/covid-green-app/issues/418
