### ISSUE TITLE
Learn how to keep others safe. Icons and visual bug in all languages EXCEPT english

### ISSUE THREAD

**Issue by helloantoine** [covid-alert-ny/covid-green-app#346]
Issue: Learn how to keep others safe. Icons and visual bug in all languages EXCEPT english
![Screenshot_20200907-123650_Pixel_Launcher](https://user-images.githubusercontent.com/16833643/92383996-371e0200-f107-11ea-9fcf-901c5d970360.png)

**Comment by ckiss** [comment]
fixed, avail in next release

**Comment by helloantoine** [comment]
Looks good to me. Thank you Cristian.
