### ISSUE TITLE
Improve Translation Import/Export

### ISSUE THREAD

**Issue by ShaunBaker** [covid-alert-ny/covid-green-app#35]
We currently have some simple script to import and export text content for the app in various languages.

As discussed in https://github.com/project-vagabond/covid-green-app/pull/32/ this issue collects the improvements to be implemented.

* Make the import/export scripts DRY
* Make the import/export scripts not dependant on hardcoded language definitions (eg read from spreadsheet columns/files in directory)

**Comment by kevin-sheldon** [comment]
Is this still an open item? It is not assigned to anyone. @ShaunBaker @dharding

**Comment by fahd-arshad** [comment]
@colmharte @fiacc who should take this on if it is still important to do?

**Comment by colmharte** [comment]
Closing this as not required at this stage
