### ISSUE TITLE
SMS Text Update

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#353]
Based on Usability Testing, please kindly update the SMS text as follows:
NYS Dept of Health: Open COVID Alert NY app. Go to My COVID Alerts tab. Tap “What to do if you test positive for COVID-19”. Scroll to bottom to enter [code]

**Comment by ahurworth** [comment]
Also looping in @mboskin to trigger a translation update.

**Comment by fahd-arshad** [comment]
I can confirm that the two SMSs I got today were using the updated text.
