### ISSUE TITLE
Change NYS Health Hotline tel number and title

### ISSUE THREAD

**Issue by fahd-arshad** [covid-alert-ny/covid-green-app#366]
NYS has set up a separate call-in number for the COVID Alert NY app users to call in. Please change any instance of "NYS Health Hotline" CTA to "COVID Alert NY Hotline" and change the number dialed to +1-833-208-4159. 

Some (but not necessarily all places this is found):
My COVID Alerts -> Learn how to keep others safe (bottom of the page)
Proximity alert landing page bottom
My Health Log -> (report symptoms) -> text and blue link: Call your doctor or **the NYS Health Hotline at 1-888-**.

**Comment by ckiss** [comment]
fixed, avail in next build

**Comment by fahd-arshad** [comment]
Seems fixed in builds 35 on iOS and Android. Thank you for the quick turnaround!
