### ISSUE TITLE
7-day Average Line Disappeared

### ISSUE THREAD

**Issue by kevin-sheldon** [covid-alert-ny/covid-green-app#374]
I no longer see the 7 Day Average lines on the Total Persons Tested and Percent Tested Positive Graphs. 

![7day](https://user-images.githubusercontent.com/69158966/92607341-00b8c200-f282-11ea-95d2-acf8c9cfac09.jpg)

**Comment by AlanSl** [comment]
This should be fixed in the next build. 

Also, if you get the build from this morning and see an issue with the 7-day average line being obviously wrong on the statewide charts (but right on the county charts), that's also fixed in the next build.

**Comment by fahd-arshad** [comment]
Closing on Kevin's behalf. Looks good in builds 35 on both iOS and Android.
