### ISSUE TITLE
The 6-digit positive code should expire in 1 hour, not 24 hours

### ISSUE THREAD

**Issue by fahd-arshad** [covid-alert-ny/covid-green-app#378]
NYS is making the call that the 6-digit positive code should expire in 1 hour, not 24 hours (as it is today) or 10 mins.

**Comment by segfault** [comment]
@rgormley I believe this is `code_lifetime_mins` in the infrastructure deploy terraform.
cc/ @dgonzalez to double check.

**Comment by dgonzalez** [comment]
It is. That configures the timeout of the code.

**Comment by rgormley** [comment]
I am making this change now.

**Comment by rgormley** [comment]
This change has been pushed and is live in `nys-dev`, `nys-qa` and `nys-prod`.

**Comment by fahd-arshad** [comment]
I just generated a code through Postman and it came with an expiry timestamp of 1599804921, which is still 24 hours. How do I validate this?

**Comment by rgormley** [comment]
I'll review this with @dgonzalez this morning.

**Comment by segfault** [comment]
We may need to restart the push api ECS instances so that they pick up the setting. I believe it's only read at startup.

**Comment by fahd-arshad** [comment]
Generated a code and confirmed TTL is 1 hour.
