### ISSUE TITLE
Updates to charts: Make Positivity Chart First, Add Most recent data point in each chart

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#379]
Two updates:
- Please re-order the charts: Percent Tested Positive first, followed by total persons tested then total tested positive.
- Add the most recent data point and color the final bar in each chart.  @helloantoine will provide the specs.

![image](https://user-images.githubusercontent.com/68069959/92618414-54c9a380-f28e-11ea-984b-86094d02991f.png)

**Comment by helloantoine** [comment]
**Design specs are here:** https://zpl.io/VQwX9PR
- [ ] Card height is higher (see screenshot)
- [ ] Graphs's last bar is highlighted
- [ ] Value of the last entry is displayed in a bubble above the graph
- [ ] X-Axis only shows 3 dates (regular font), correctly aligned with the bar (and using a vertical line for each date)
- [ ] Legend square for Daily figure is smaller
- [ ] Accessibility: Make sure to cap font size of the value
- [ ] Accessibility: Make sure the value of the last entry is read with Voiceover
- [ ] Re-order the charts. % tested positive, then total tested positive, then total test

![Screenshot 2020-09-10 at 11 04 39](https://user-images.githubusercontent.com/16833643/92715508-7477cf00-f355-11ea-93ac-55943465de51.png)

**Comment by AlanSl** [comment]
@JohnAGill Suggestion: in `molecules/bar-chart.tsx` remove the comment from above the intervals count and set it to:

```
  const intervalsCount = Math.round(daysLimit / 2);
```

We don't (🤞) need to worry about the 29 days case any more, we're now getting more than 30 days.

**Comment by JohnAGill** [comment]
This has been added and should be in the next build

**Comment by helloantoine** [comment]
Looks good to me.
