### ISSUE TITLE
Add a Feedback Button 

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#381]
A user with feedback has no way to provide feedback to us, other than very publicly in an App/Play Store review.

We should add a "Submit Feedback" button which would launch the installed mail client.

To: [Needed: email address @fahd-arshad to arrange with NYS.]
Subject line: App Feedback for COVID Alert NY: Version [version number]
Body:
[five lines of blank space to allow the user to supply comments, followed by the following diagnostics data, automatically detected by the system)

- App Version
- Device Make & Model
- OS Version & Play Services Version (Android only)
- Native Version
- JS Version
- Status of EN framework (enabled or not) - if possible 
- Bluetooth active (yes/no) - if possible 

Here's a format we can follow:
![Screenshot_20200909-113221](https://user-images.githubusercontent.com/68069959/92620068-3cf31f00-f290-11ea-9c65-f6b86d72deaf.png)

![image](https://user-images.githubusercontent.com/68069959/92628361-ae37cf80-f29a-11ea-83ab-c6c9880786ca.png)

**Comment by fahd-arshad** [comment]
covidalertny@health.ny.gov is the mailbox. This has NYS approval. Pls proceed.

**Comment by kevin-sheldon** [comment]
Confirming Fahd's comment. This has been approved by NYSDOH.

**Comment by JohnAGill** [comment]
This has been added and will be in the next build

**Comment by helloantoine** [comment]
Looks good to me

**Comment by ahurworth** [comment]
I'm seeing some issues with the diagnostics within the email body, which i was expecting to be more human readable?   Otherwise looks great!  Thanks for the quick turnaround.

![Screenshot_20200911-144702](https://user-images.githubusercontent.com/68069959/92968350-f1d03c00-f448-11ea-8a15-2a1538268cea.png)

**Comment by floridemai** [comment]
> I'm seeing some issues with the diagnostics within the email body, which i was expecting to be more human readable?

@ahurworth If you are referring to the "ENS Details" text that has a lot of `{`, it was my suggestion to do it like this. I think we're interested in us getting the full details rather than it looking good on the screen. Of-course we can do something like:
```
Can support? Yes
Supported? Yes
Enabled? Yes
Exposure permission status: Allowed
...
```
But imho those terms would just confuse the user more.

Let me know what you think.

**Comment by kevin-sheldon** [comment]
@ahurworth  can you comment on this?

**Comment by kevin-sheldon** [comment]
Details of the enhancement to this is outlined in #421

**Comment by ahurworth** [comment]
Thanks for elaborating, @floridemai .  

First and foremost, we should optimize for getting the most granular data necessary for diagnosing issues by users.  So your more granular version is better than my original suggestion.  

Having said that, any user that's not an Engineer by profession will look at that debug log and not understand it.  Similar to the `<br><br><br>` at the top, it feels like something is there that should not be there, and it creates the impression that something isn't working / there is a bug, or worse still: that something is being shared that I may not want to share.  

So I like your suggestion of making it more human-readable - as long as that does not remove any crucial details that Engineers will need to troubleshoot any issue reported by a user.

**Comment by AlanSl** [comment]
@ahurworth and @helloantoine We've got the screens flow for this set up in build 41 which you can try, and we're iterating on the format of the email (I believe John has sent you a proposal there). The new text for these screens has been sent out for the translators by Kevin.

**Comment by ahurworth** [comment]
Great!  Thanks!
@kevin-sheldon we're proposing adding a title above the diagnostics information so that the user is less confused about why the information is there.  Let us know if you have any objections with:

`Please do not remove. This info helps the technical team assist you:`

**Comment by JohnAGill** [comment]
Ive updated the body of the email to include a message explaining what this is and made the fields a lot more readable so that users don't think we're doing anything untoward. Should be included in the next build

**Comment by AlanSl** [comment]
@kevin-sheldon @ahurworth @helloantoine Can you please try out the implementation of this in Build 42 (released today)

**Comment by helloantoine** [comment]
Looks good. Thanks!
