### ISSUE TITLE
App Crashes trying to enable COVID Alerts After choosing Skip for now

### ISSUE THREAD

**Issue by mboskin** [covid-alert-ny/covid-green-app#386]
The following might have been fixed in a subsequent release. 

After choosing Skip for Now during onboarding attempting to click the orange banner to set up My Covid Alerts at the landing screen causes the app to crash. Closeness sensing can still be turned on from the App Settings under My COVID Alerts. Crash is repeatable, just turning off closeness sensing and then returning to the landing page to click the orange banner causes it.   

Bug number 29 |   | 1.0.0 (29) | Android | Galaxy S10+ | 9/3/20 4:13 PM | Patrick Brennan

**Comment by ckiss** [comment]
@mboskin I am pretty sure this was fixed already(it was probably the issue with the chart on the dashboard that caused this). I can't repro anymore.

**Comment by mboskin** [comment]
Retest passed. Issue is closed.
