### ISSUE TITLE
County Picker can be made to display "Choose your county" instead of the currently displayed county on landing screen

### ISSUE THREAD

**Issue by mboskin** [covid-alert-ny/covid-green-app#387]
Reproduced by opening the county picker and entering a junk search that returns nothing then pressing the 'enter' button for the text app (could be different for other text apps I use the default and its a blue check mark), then hitting the 'X' in the upper left of the screen. Instead of displaying text for the current county data the picker will show "Choose your county"

Bug 30 |   | Build/release 1.0.0 (33) | Android | Galaxy S10+ | 9/8/20 4:27 PM | Patrick Brennan

**Comment by ckiss** [comment]
@mboskin I can't reproduce this on my android phone. Can you double check this?

**Comment by mboskin** [comment]
Patrick,

Can you double check this issue? Given your S10+ is obviously not out-of-date.

Thanks,
Mike
_____________________

[REDACTED}
*Removed e-mail signature as the e-mail reply feature was used*

**Comment by AlanSl** [comment]
I also can't replicate this, on a Samsung running Android 9, trying a variety of keyboard apps. 

Looking at the code I suspect this may have been possible back when "All counties" was excluded as an option on typing non-matching text, but should not now be possible now that "All counties" is always present as an option.

**Comment by mboskin** [comment]
I have marked it for retesting.

_____________________

[REDACTED}
*Removed e-mail signature as the e-mail reply feature was used*

**Comment by floridemai** [comment]
@AlanSl @mboskin Thanks to @ckiss I was able to reproduce it. It's related to what Alan suggested but for that you need to select a county first. PR to come and fix will be available in the next build

**Comment by floridemai** [comment]
@mboskin Done. Ready to be tested in the build to come.

**Comment by helloantoine** [comment]
Looks solved.
