### ISSUE TITLE
Proximity Alert Drill In Screen: "Back" button should take the user to the COVID Alerts tab Root

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#393]
As reported by Bonnie, on receiving the proximity alert notification screen and tapping on it, she lands on the proximity alert detail screen as expected.  On hitting "back" she is taken to the screen prompting her to share her keys.  I suspect this is because the "back" is taking her to the retained state of the app i.e. the most recent screen she visited.  

"Back" on the proximity alert landing screen should take the user to the root of the COVID Alerts tab.  This is important behavior as the user needs to know where they can find the red banner that allows them to come back to the drill in screen later if they choose to.  It has been evaluated through a number of usability testing studies.

**Comment by ckiss** [comment]
fixed, avail in next build

**Comment by ahurworth** [comment]
Works, thanks!  One side effect though is on Android.  New bug issue opened: https://github.com/project-vagabond/covid-green-app/issues/446
