### ISSUE TITLE
Copy Update: On-boarding Screen 1

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#397]
As a result of the Columbia field trial, we would like to change the wording on the very first on-boarding screen
 
FROM: "We don't collect info that can identify you.  Your identity and location are always confidential" 

TO: "We don't collect info that can identify you.  The app never tracks your location."

**Comment by ckiss** [comment]
fixed, avail in next build

**Comment by helloantoine** [comment]
Looks good. Needs translations though.
