### ISSUE TITLE
Configure APNS Entitlement for iOS builds

### ISSUE THREAD

**Issue by dharding** [covid-alert-ny/covid-green-app#4]
The current project setup does not include an APNS entitlement. This can be added, but I do not want to add it unless we are actually planning to use remote push notifications in the NY app. Until that time, App Store Connect will send a warning for all uploaded builds that the app uses APNS but does not have the entitlement. You can ignore this for internal TestFlight builds for the time being.

**Comment by davidjharding** [comment]
I have removed APNS from the key since we are not planning to use it.
