### ISSUE TITLE
Configure NetInfo to use our API for internet reachability test

### ISSUE THREAD

**Issue by dharding** [covid-alert-ny/covid-green-app#404]
We need to use `NetInfo.configure()` to set the `reachabilityUrl` to our own API rather than calling the default Google-hosted URL. This was something that was raised by the community when another COVID exposure notification app was released.

**Comment by segfault** [comment]
The other app's ticket is here: https://github.com/cds-snc/covid-alert-app/pull/1004

**Comment by floridemai** [comment]
Build 43 has this applied

**Comment by AlanSl** [comment]
Closing this as @dharding has confirmed by moving it to done
