### ISSUE TITLE
On launch of Landing Screen warning for closeness alert being turned off shows momentarily even though it has already been turned on

### ISSUE THREAD

**Issue by mboskin** [covid-alert-ny/covid-green-app#408]
Only occurs on launch of app when launching the landing page, goes away after a short loading icon. Does not reoccur until app is launched again.

Bug 32 |   | 1.0.0 Build/release(35) | Android | Galaxy S10+ | 9/10/20 5:26 AM | Patrick Brennan

**Comment by floridemai** [comment]
@mboskin This has been raised in another ticket. And fixed. Can you check it again please?

**Comment by mboskin** [comment]
This has been added to the MS-Teams list of issues for ITS to retest.

[REDACTED]
*Removed e-mail signature content*
