### ISSUE TITLE
Bug. Orange banner flashing issue in the Data tab on Android and iOS

### ISSUE THREAD

**Issue by helloantoine** [covid-alert-ny/covid-green-app#415]
**Issue:** Orange banner flashing issue in the Data tab on Android and iOS
**Steps:** Make sure your COVID Alerts is not working. Then go to COVID Data tab. Get out of the app and then get in again.
[ScreenRec_20200911_154958.mp4.zip](https://github.com/project-vagabond/covid-green-app/files/5209747/ScreenRec_20200911_154958.mp4.zip)

**Comment by floridemai** [comment]
@helloantoine Can you validate this in the next build?

**Comment by helloantoine** [comment]
I cannot reproduce this. Well done.
