### ISSUE TITLE
Copy Update: User has turned off Bluetooth

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#417]
For the scenario where the Bluetooth has been turned off post-onboarding: 

Currently we display the yellow banner on the NY COVID Data tab with a generic message that is used for other scenarios (like where notifications are not turned on).

We'd like the wording to be more specific for this scenario - especially considering many people are likely to toggle BT on/off throughout the day/week.  The new wording is:
"To get COVID Alerts you must enable Bluetooth.  Tap to learn more."

The behavior when tapping the yellow banner will stay the same for now i.e. it will land on the COVID Alerts tab and the same red card will appear today indicating where users should go to re-enable their Bluetooth (which will be important for iOS users as they shouldn't change via Control Center).  Ultimately we can take them directly Settings, but let's minimize the change/risk for now.

@helloantoine will attach and image shortly.

I'm also tagging @mboskin @kevin-sheldon for updates to the translations.

**Comment by helloantoine** [comment]
![Bluetooth granular msg](https://user-images.githubusercontent.com/16833643/92948358-234d0580-f451-11ea-8a0d-8e9bd666f6e0.png)

[bluetooth-icon.svg.zip](https://github.com/project-vagabond/covid-green-app/files/5210246/bluetooth-icon.svg.zip)

**Comment by ckiss** [comment]
fixed, avail in next build

**Comment by helloantoine** [comment]
Looks good to me. Thank you.
