### ISSUE TITLE
Adjust spacing of intro screen so that CTA is visible on iPhone SE

### ISSUE THREAD

**Issue by helloantoine** [covid-alert-ny/covid-green-app#418]
Main CTA for iPhone SE is below the fold, and could be missed easily. Let's compress about the spacing for everyone so this doesn't happen. 
![Screenshot 2020-09-11 at 17 38 20](https://user-images.githubusercontent.com/16833643/92951056-ab350e80-f455-11ea-8ca8-505cf162e9b6.png)

**Comment by ckiss** [comment]
fixed, avail in next build

**Comment by helloantoine** [comment]
Looks good to me. Thank you
