### ISSUE TITLE
Ethnicity options have two typos

### ISSUE THREAD

**Issue by mboskin** [covid-alert-ny/covid-green-app#419]
Ethnicity has two typos instead of Latino it says Hispanic/Latinx and Not Hispanic/Latinx. It is located in App Settings->My Health Log->Ethnicity

Bug 33 | 1.0.0.37 | Android | Samsung Note 8 | 9/11/20 12:50 PM | Gracjan Nawrot

**Comment by kevin-sheldon** [comment]
Hi Mike - Latinx is a gender-neutral term, and is accurate for this release. 

Closing ticket.
