### ISSUE TITLE
Incorrect phone number for NY State Covid-19 Hotline

### ISSUE THREAD

**Issue by mboskin** [covid-alert-ny/covid-green-app#420]
When you go to My COVID Alerts->Learn how to keep other safe, scroll down to the bottom, click "If you need more help, call COVID Alert NY Hotline" which shows phone number 1-833-208-4159. When you call this number you get following recording "The number you have reached has been reserved by New York State Department of Taxation and Finance". The actual phone number to NY State COVID-19 Hotline is 1-888-364-3065.

Bug 34 | Open | 1.0.0.37 | Android | Samsung Note 8 | 9/11/20 1:18 PM | Gracjan Nawrot

**Comment by kevin-sheldon** [comment]
Hi Mike - There is a completely separate number for COVID Alert NY. 

The correct number is 1-833-208-4159

This is a brand new number.  Issue 366 covered this and was closed. 

Closing this ticket.

**Comment by mboskin** [comment]
Thanks

[REDACTED}
*Removed e-mail signature as the e-mail reply feature was used*
