### ISSUE TITLE
Enhancement to Feedback Option

### ISSUE THREAD

**Issue by kevin-sheldon** [covid-alert-ny/covid-green-app#421]
Requesting enhancement to https://github.com/project-vagabond/covid-green-app/issues/381

In addition to the new functionality in ticket #381 , requesting an additional landing screen for a user to specify the type of feedback that they are submitting. Based on the selection, that will be added to the e-mail subject line. 

Please see attached mockup for an example. 

Also, requesting additional pre-populated info in the e-mail body instructing a user to not submit Protected Health Information (PHI) or Personally Identifiable Information (PII) in their request. 

We may want to also ask users to submit a screenshot if they are reporting an issue.

**Comment by kevin-sheldon** [comment]
Need to provide you with the approved list of options to choose from in Middle Screen (in attached image)

**Comment by kevin-sheldon** [comment]
For the choices, the subject line in the e-mail when selected should translate to:

Enhancement Suggestion = Enhancement
Report an Issue = Issue
General Feedback = General

**Comment by kevin-sheldon** [comment]
Final List:

Enhancement Suggestion
Report an Issue
General Feedback

**Comment by helloantoine** [comment]
Works as expected. I ll add some visuals tweaks in a separate ticket. Discussed with Alan.
