### ISSUE TITLE
Update graphs. 1% and label update

### ISSUE THREAD

**Issue by helloantoine** [covid-alert-ny/covid-green-app#425]
**Issues:** 
1. In some scenarios, the graph is missing a top value on the Y-axis. 
2. Label looks very far from the bar itself when value is low and label positioned at the top right corner

**Solutions**
1.  Set 1% as the minimum for the top Y axis value
2. Make label position dynamic, close to the bar itself, with 0.9 opacity

**Comment by AlanSl** [comment]
Wasn't expecting you to merge PR https://github.com/project-vagabond/covid-green-app/pull/426, just check the screenshots... Normally PR author merges after reviews. I take it you're happy with it then?

**Comment by helloantoine** [comment]
Understood. Thanks Alan

**Comment by helloantoine** [comment]
Looks good to me/
