### ISSUE TITLE
Putting the English names in parenthesis

### ISSUE THREAD

**Issue by mboskin** [covid-alert-ny/covid-green-app#433]
This is Fahd.

The list of languages here is indeed the list given to us as the top 7 NYS languages required by the https://www.ny.gov/language-access-policy. I believe it covers the ones you have listed; I do not know if the translation of Chinese actually is Mandarin or Cantonese, but Steven (cc'ed) would know. Also, Italian isn't on the list based on the page above. 

NYC has a larger set which includes right-to-left languages, so we decided to aim for that on the second version of the app: https://www1.nyc.gov/site/planning/about/language-access.page

Your idea for putting the English names in parenthesis is a good one. @Boskin, Michael (HEALTH) would you mind putting this in as an enhancement issue? It should be easy since it's content only.

**Comment by kevin-sheldon** [comment]
I will add design for this in a few minutes

**Comment by kevin-sheldon** [comment]
[My Language.docx](https://github.com/project-vagabond/covid-green-app/files/5219717/My.Language.docx)

On the settings menu, for all languages besides English, please make sure that the English translation "My Language" appears in parenthesis (see first image in attachment). 

On the language selection menu, please make sure the English translation of all non-English languages is in parenthesis. See the "Espanol (Spanish)" line as an example in the attachment.

**Comment by fahd-arshad** [comment]
Looks good to me. Assigning to @floridemai since he's been dealing with most of the translation issues and this is close to that. Please reassign as needed.

**Comment by AlanSl** [comment]
This is done in https://github.com/project-vagabond/covid-green-app/pull/439 and should be in the next build.

I used the English names for the languages as given on https://www.ny.gov/language-access-policy

**Comment by mboskin** [comment]
Marked as closed ass per AlanSI

**Comment by kevin-sheldon** [comment]
Reopening until this can be tested by our team. I do not see this in Build 40. Awaiting confirmation on which build this is going into.

**Comment by AlanSl** [comment]
@kevin-sheldon I was expecting a new build yesterday but there wasn't one. I've made a new build just now, 41, which should include this. Available on Android now and iOS shortly.

**Comment by helloantoine** [comment]
Looks good to me. Thank you!

**Comment by kevin-sheldon** [comment]
Looks great guys!! Closing.
