### ISSUE TITLE
App Store Translations

### ISSUE THREAD

**Issue by kevin-sheldon** [covid-alert-ny/covid-green-app#434]
Once DOH Marketing team has provided copy, need to ensure that App Store and Play Store is translated appropriately. 

Will get final copy over to translators once provided.

Logging this ticket as a placeholder.

**Comment by helloantoine** [comment]
@kevin-sheldon @fahd-arshad 
I'm attaching a preview of all the files generated in the 7 languages. 
Each preview shows: 
5 screenshots for 5.5 inch devices. 
5 screens for 6.5 inch devices. 
5 screens for android screens. 
And one Android promo screen.

Easy. I couldn t attach them here but you can download them here:
https://drive.google.com/file/d/1CIH8EJkE5f1e_0GumdxcCmh2FrGavWSV/view?usp=sharing

**Comment by AlanSl** [comment]
@helloantoine @kevin-sheldon I believe this is done now? Can it be closed? 

We may need to open another issue for the translations of boilerplate text for describing app updates but I think that's best done in its own issue.
