### ISSUE TITLE
Minor Visual: Update Chart Callout Numbers with Commas

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#437]
Could we add some formatting so that comas are inserted after every 3 numbers?

For example: in the second chart, 72668 would be 72,668.
Please make sure the callout element will support the display of up to 8 figures (I hope we won't ever need it, but just in case!) + commas without breaking i.e. up to 99,999,999.

![IMG_3C2634D282AC-1](https://user-images.githubusercontent.com/68069959/93111870-3fd18380-f685-11ea-97c2-567af81ab7ec.jpeg)

**Comment by AlanSl** [comment]
Done in https://github.com/project-vagabond/covid-green-app/pull/440 should be in next build.

**Comment by helloantoine** [comment]
Looks good to me. Nice one.
