### ISSUE TITLE
Proximity Alert Notification Flow on Android Bug

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#446]
When I tap on the proximity notification, I land on a drilled in screen showing the quarantine steps that I should follow. If I hit "back" I land on the COVID Alerts tab.  On Android however, I see a rogue "back" button on the COVID Alerts tab, which doesn't do anything, and shouldn't be present. I should be at the root of the stack.  

Per @helloantoine, iOS is working fine, only Android is affected.  Note however, that these tests were conducted as a result of triggering the notification from the Debug menu.  (In case this is an important detail)
 
![Screenshot_20200915-080329](https://user-images.githubusercontent.com/68069959/93222843-6521c880-f73d-11ea-8fcf-5d6acc932053.png)

**Comment by AlanSl** [comment]
Should be fixed in the build we're pushing out now (build 41)

**Comment by ahurworth** [comment]
Great.  Thanks.  Confirmed as fixed.
