### ISSUE TITLE
Yellow Banner Seen Momentarily on App Launch (iOS and Android)

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#447]
I see the yellow banner display momentarily on launching the app.  I tried deleting the app and creating a fresh install, but it didn't change anything.  Running build 40. 

See video:

[20200915-110220-720x1520_3.mp4.zip](https://github.com/project-vagabond/covid-green-app/files/5225897/20200915-110220-720x1520_3.mp4.zip)

**Comment by floridemai** [comment]
Duplicate of https://github.com/project-vagabond/covid-green-app/issues/415.
The question is: yellow or orange? 😂  @ahurworth @helloantoine

**Comment by floridemai** [comment]
@ahurworth Should be fixed in the next release.

**Comment by ahurworth** [comment]
I no longer see the flash of the (amber!? :) ) banner
