### ISSUE TITLE
Cosmetic issues. A bundle of small issues

### ISSUE THREAD

**Issue by helloantoine** [covid-alert-ny/covid-green-app#453]
- [x] a. On the graph, months are sometimes cropped
- [x] b. If you test positive. Can we divide by half the spacing flagged. Especially the one between the CTA and the text.
- [x] c. In Korean, in the learn how to protect others, these characters are not interpreted
- [x] d. In Spanish, for the menu item ONLY, I got confirmation we can truncate the text to: "Config. de la aplicación"
- [x] e. In Spanish, link should be on the text: **Encuentre un sitio cernano a usted** not separate.

![small-issues](https://user-images.githubusercontent.com/16833643/93313801-d6767f80-f800-11ea-992a-4e4413520e8a.png)

- [x] g.Tweak the Submit Feedback screen. Make button primary purple and tweak spacing. (mockup to come)

**Comment by helloantoine** [comment]
![settings-languages copy 2](https://user-images.githubusercontent.com/16833643/93367731-d009f700-f844-11ea-9389-cafb11e022fb.png)

**Comment by helloantoine** [comment]
+1 please:
- [x] Update NY to NYS in the Health Log first time disclaimer screen in all languages

**Comment by AlanSl** [comment]
@helloantoine I can't replicate the SVG issue on my devices or simulator, can you move it to a separate low priority issue so we can box this off and someone else can pick it up?

<strike>Same with the korean characters - another separate issue as it might need to go back to the translators</strike> nevermind, fixed

**Comment by AlanSl** [comment]
Done (except the initial SVG issue as discussed), going in the next build

**Comment by helloantoine** [comment]
Excellent. Thank you.
