### ISSUE TITLE
Incorrect message in orange banner when notifications are off

### ISSUE THREAD

**Issue by helloantoine** [covid-alert-ny/covid-green-app#459]
Issue: Incorrect message in orange banner when notifications are off
Steps: switch off notifications for the NY app on your device settings. Go back to the app.
Solution: Display generic orange banner (app can't alert you...)
@floridemai @ahurworth 
![image](https://user-images.githubusercontent.com/16833643/93395913-ac5ba680-f86e-11ea-801c-949527ac7782.png)

**Comment by AlanSl** [comment]
Seems to work on Android so it looks like this is iOS only.

![Screenshot_20200918-080852_Settings](https://user-images.githubusercontent.com/29628323/93432184-1307b100-f8bd-11ea-8e13-e27b3bcf5936.jpg)

**Comment by floridemai** [comment]
@helloantoine Should be fixed in build 43.

**Comment by helloantoine** [comment]
Fixed indeed. Thanks!
