### ISSUE TITLE
Cosmetic. Flashing Health Log card

### ISSUE THREAD

**Issue by helloantoine** [covid-alert-ny/covid-green-app#463]
**Issue:** Health Log flashes then disappears
**Steps**Android. Do a full health check. Close the app. Reopen the app
**Solution** Not sure how it's done technically. If you can apply the same 'fix' you did for the orange banner, that'd be great.
[flashing-health-log.mp4.zip](https://github.com/project-vagabond/covid-green-app/files/5237824/flashing-health-log.mp4.zip)

**Comment by AlanSl** [comment]
Should be fixed in build 42

**Comment by helloantoine** [comment]
Fixed indeed. Thank you.
