### ISSUE TITLE
Change Code Expiration Message

### ISSUE THREAD

**Issue by kevin-sheldon** [covid-alert-ny/covid-green-app#468]
Current message says to contact HSE for a new code. 

![image](https://user-images.githubusercontent.com/69158966/93515858-3f402380-f8f7-11ea-9eae-8e1247746ba3.png)

Please change "HSE" to "DOH"

Also needs the translated text for "DOH" (which I think we have already provided)

**Comment by AlanSl** [comment]
Changed, should show in build 44. 

I checked all other languages too and they were fine as expected, problem was only English.

**Comment by kevin-sheldon** [comment]
Language changed to DOH. Closing.
