### ISSUE TITLE
Update the Close Contact Alert landing screen

### ISSUE THREAD

**Issue by fahd-arshad** [covid-alert-ny/covid-green-app#470]
Please see the attached request from NYS. @helloantoine if you can kindly mock this up first thing and send to NYS stakeholders (in your email inbox) for approval, we can get it over to the developers. Thank you. 

[Update the Close Contact Alert landing screen.pdf](https://github.com/project-vagabond/covid-green-app/files/5243347/Update.the.Close.Contact.Alert.landing.screen.pdf)

**Comment by fahd-arshad** [comment]
Language so you can copy/paste:

You have received an alert because you have been in contact with someone with COVID-19. There may be a risk you’ll develop COVID-19, so you should quarantine yourself at home, talk to your doctor, and call COVID Alert NY Hotline to find out how to protect yourself and others.


**Get tested.** 
Talk to your healthcare provider to schedule an appointment.
[Find a test site near you.](https://coronavirus.health.ny.gov/find-test-site-near-you)

**Call the Hotline.**
Call the COVID Alert NY Hotline for more information or to schedule a test at a NYS test site.
[1-888-208-4159](http://1-888-208-4159)

**Stay home. 
Stay home for 14 days except to seek medical care and get a COVID test.

**Comment by helloantoine** [comment]
Thank you @fahd-arshad . Mockup of the updated screen available here: 
https://nearform.invisionapp.com/console/share/NZY402QAG3Q/428104629

**Comment by floridemai** [comment]
Available in build 44
