### ISSUE TITLE
Copy Updates to the Health Log Intro Screen

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#478]
We have updated copy for the intro screen to the Health Log.

[Title] My Health Log

My Health Log lets you keep track of your own health by storing a history of your symptoms.

The anonymous daily logs from you and other app users help public health research understand how the virus is affecting NYS.

<b>This does not reveal your identity.</b>

[Button] Get Started

@helloantoine @fahd-arshad

**Comment by helloantoine** [comment]
Screen updated in Invision https://nearform.invisionapp.com/console/share/NZY402QAG3Q/428110489

**Comment by floridemai** [comment]
Available in build 44

**Comment by ahurworth** [comment]
Minor tweak, could we change "public health research" to "public health researchers"

The anonymous daily logs from you and other app users help public health research**ers** understand how the virus is affecting NYS.

@fahd-arshad

**Comment by floridemai** [comment]
@ahurworth Is it possible to have another issue created just for this. Just because we need the translations for this too unfortunately :(

**Comment by ahurworth** [comment]
Done, but since I'm only just seeing this now, does it mean we missed the translation 5?

https://github.com/project-vagabond/covid-green-app/issues/490

**Comment by floridemai** [comment]
@AlanSl ^^ ?
