### ISSUE TITLE
Change the COVID Alert NY Hotline number to 833-227-5045

### ISSUE THREAD

**Issue by fahd-arshad** [covid-alert-ny/covid-green-app#479]
Please change the COVID Alert NY Hotline number to 833-227-5045. This shows up in a number of places in the app, such as the close contact notification, the "help others" instructions, and the health log having symptoms page, off the top of my head. Please change both the displayed number (where applicable) and the number that's called.

**Comment by floridemai** [comment]
Available in build 44

**Comment by fahd-arshad** [comment]
I checked the Close Contact Alert, the Health Log symptoms response, and thee help others screens and the number is updated. @mboskin assigning to you so we can please validate this as part of NYS's testing.

**Comment by mboskin** [comment]
Added to the MS-Teams list for retesting

_____________________

[REDACTED]
*Edited* to protect this project's data privacy policy
