### ISSUE TITLE
The privacy policy in build 12 is incorrect

### ISSUE THREAD

**Issue by fahd-arshad** [covid-alert-ny/covid-green-app#48]
It should be the short version written out at https://nearform.invisionapp.com/d/main#/console/20287854/428431587/build. At the bottom of that page is a link that should go go to the longer policy on the web: https://apps.health.ny.gov/public/covidsmartprivacy.html

**Comment by fahd-arshad** [comment]
Also, the title of the policy is in the body and should not be "Data Protection Information Notice". We don't use the term "DPIN" anywhere.

**Comment by fahd-arshad** [comment]
### Data and Privacy Policy

Your privacy and data security are very important to the New York State Department of Health. The COVID Alert NY app protects the privacy of all app users, at all times.

**You remain anonymous to us and other app users. The app does not allow us or anyone else to:**
- Collect your name, address, or any other personally identifiable information.
- Track your location.
- Access any information on your phone outside of this app.

**It’s always your own personal choice to:**
- Use the app or not.
- Share your demographics and symptoms in the health log.

<icon> [Read our comprehensive privacy policy](https://CovidAlertNY.health.ny.gov/PrivacyPolicy.html)

![in-app privacy policy](https://user-images.githubusercontent.com/68031284/91478989-aa955900-e855-11ea-946a-fe5c095f1464.png)

**Comment by fahd-arshad** [comment]
@segfault FYI I updated the URL above to https://CovidAlertNY.health.ny.gov/PrivacyPolicy.html.

**Comment by AlanSl** [comment]
We're getting this in the app from the API now, in English. @segfault will you be adding the translated versions to the API?

The display isn't matching the designs, so I'm going to work on that now for the next build, but the content is there.

**Comment by AlanSl** [comment]
From today's build the data policy should show the latest from the API, styled as above, and we're getting the English translation through in the app already. All links to it have been changed to use the correct name.

![image](https://user-images.githubusercontent.com/29628323/91643580-7031e480-ea2c-11ea-9ab0-4c8d6dd79a5a.png)

**Comment by kevin-sheldon** [comment]
This  looks good from my end. @fahd-arshad can we close this?

**Comment by fahd-arshad** [comment]
Yes. I can confirm this is in good shape now.
