### ISSUE TITLE
Label Change to Feedback Option

### ISSUE THREAD

**Issue by kevin-sheldon** [covid-alert-ny/covid-green-app#486]
Will provide copy signoff ASAP, but looking to add some more instructional text to the Submit Feedback page under "What type of feedback would you like to submit?"

Draft copy:

"NOTE: This is for technical feedback only and will be shared with our app developers. 

If you are feeling sick or have general questions about COVID-19, please do not use this feedback option and call the COVID Alert NY Hotline instead at 1-833-227-5045"

We would like the hotline number as an actionable item where a user can select and it initiates a call (similar to the other screens that we have the hotline number on)

**Comment by kevin-sheldon** [comment]
I would defer to @ahurworth  and @helloantoine  on the design but the disclaimer/note could also come above the "What type of feedback would you like to submit?" question if we feel like the user should read that first. 

Not sure if it also makes sense to put the disclaimer in red text

**Comment by AlanSl** [comment]
@helloantoine @ahurworth I've put this together in draft form to ease generating the translations spreadsheet; here's how it would look with default formatting except bold on the "NOTE":

<img width=450 src="https://user-images.githubusercontent.com/29628323/93792029-e3dea000-fc2c-11ea-929b-f990a4be4c0b.jpg" />

**Comment by helloantoine** [comment]
Please: @AlanSl 
> Increase spacing between paragraph and the question
> Make question in bold

**Comment by helloantoine** [comment]
Loooks good otherwise thx

**Comment by kevin-sheldon** [comment]
@helloantoine @AlanSl  Mahesh has provided signoff on the copy that I included in this ticket. No changes are needed. 

Mockup looks good. OK to move forward.

**Comment by AlanSl** [comment]
Done and will be in the next build.

![image](https://user-images.githubusercontent.com/29628323/93888062-6aec5080-fcdf-11ea-83eb-0125c7b87fa9.png)

**Comment by kevin-sheldon** [comment]
Tested and looks good!
