### ISSUE TITLE
Copy Tweak: Public Health Research -> Public Health Researcher on My Health Log Intro

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#490]
Minor tweak, could we change "public health research" to "public health researchers"

The anonymous daily logs from you and other app users help public health researchers understand how the virus is affecting NYS.

@fahd-arshad

Created as a new issue requested by @floridemai .

**Comment by AlanSl** [comment]
It looks like we'll need a v6 translations sheet with this and the new one-screen age gate text, I'll get assembling that

**Comment by AlanSl** [comment]
Done for English, translations requested and some received, should all be in the next build

**Comment by ahurworth** [comment]
Looks good.
