### ISSUE TITLE
Expired Positive Test Code Error Still Refers to HSE

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#491]
During the SUNY testing at the weekend, a couple of users encountered an expired code, and reported that the error message indicates "Contact HSE to request another one".

Please remove this last sentence.

@kevin-sheldon to advise if anything else is needed.

**Comment by kevin-sheldon** [comment]
Hi Alex,

I already put in a ticket to change HSE to DOH.

Thanks,
Kevin

________________________________

**Comment by kevin-sheldon** [comment]
[Image.jpeg]

**Comment by AlanSl** [comment]
Yes Kevin reported this in https://github.com/project-vagabond/covid-green-app/issues/468 and we fixed it in build 44 last week - that build wasn't pushed to the SUNY testers because it was felt it wasn't worth the disruption of them going through the app update process.

**Comment by kevin-sheldon** [comment]
The term HSE was changed to DOH. Verified in Build 46

**Comment by ahurworth** [comment]
Thanks!  Closing...
