### ISSUE TITLE
Add "the" to the close contact/exposure alert screen

### ISSUE THREAD

**Issue by fahd-arshad** [covid-alert-ny/covid-green-app#498]
In the screen below, in the second para that starts with “What do I do now”, the second-to last part currently is 
“and call COVID Alert NY Hotline”. 

0It’s missing a “the” before "COVID". Please change it to the following:

“and call **the** COVID Alert NY Hotline”. 

![image](https://user-images.githubusercontent.com/68031284/93909927-36fc3580-fcb5-11ea-929b-2d53c97029af.png)

**Comment by AlanSl** [comment]
Done will be in next build

**Comment by fahd-arshad** [comment]
Thank you Alan. Looks good in build 46 on iOS.
