### ISSUE TITLE
Define a list of test devices

### ISSUE THREAD

**Issue by dharding** [covid-alert-ny/covid-green-app#5]
As part of the AWS Device Farm configuration, we will need to define a list of devices, both Android and iOS-based, upon which our tests will be executed. I have reached out to Apple for any information they have regarding the number and types of iPhones in NYS. The Android devices would be so varied that we would be better off selecting a representative set across the most popular manufacturers and screen sizes.

**Comment by kevin-sheldon** [comment]
@dharding Can we close this. We have identified testers for both OS and with multiple screen sizes.

**Comment by davidjharding** [comment]
@kevin-sheldon we can close this for now. When we apply some more automation in the future, we will want to choose a representative set of devices on which to run tests.
