### ISSUE TITLE
My health log: if any symptoms are checked "I am feeling well" button should be disabled.

### ISSUE THREAD

**Issue by fahd-arshad** [covid-alert-ny/covid-green-app#52]
My health log: if any symptoms are checked "I am feeling well" button should be disabled. If symptoms are unchecked, it should be enabled again.

**Comment by fahd-arshad** [comment]
@mboskin @ahurworth would one of you kindly mind testing this for me and closing this out if this works? Tks.

**Comment by mboskin** [comment]
I have confirmed with Linh that his team will be testing at 4:00 today. I will mark this as ready to test.

Thanks for the notification,
Mike

_____________________


www.nystec.com<http://www.nystec.com/>

**Comment by ahurworth** [comment]
I will mark this as closed since "I'm feeling well today" is now not tappable after at least one symptom is selected, but per my discussion with @stuartgiles the styling doesn't meet the bar of perceivably "inactive" IMO.  I will create a new ticket for updating the styling.
