### ISSUE TITLE
URGENT - CHANGE PRIVACY POLICY URL

### ISSUE THREAD

**Issue by kevin-sheldon** [covid-alert-ny/covid-green-app#525]
Mark - Can you please point to the following NEW URL for the privacy policy page?

https://covidalertny.health.ny.gov/covidalert-privacy

This is has been updated by NYSDOH executive leadership. 

CRITICAL for 10/1 launch

**Comment by kevin-sheldon** [comment]
@fahd-arshad

**Comment by segfault** [comment]
This is now live. Please confirm we're good to close.

**Comment by kevin-sheldon** [comment]
Confirmed in Build 49
