### ISSUE TITLE
Skipping Demographics on My Health Log Creates Improper Default Values

### ISSUE THREAD

**Issue by kevin-sheldon** [covid-alert-ny/covid-green-app#529]
If you skip over the demographic entry screen on my health log, the app defaults to the following values:

County: Not in New York State
Gender Identity: Prefer not to say
Age range: Prefer not to say
Race: Prefer not to say
Ethnicity: Prefer not to say

Can you confirm if these values are being added to app metrics or are they being ignored? If they are being counted, then the County needs to be something other than what it is defaulting to. 

We know this cannot make it into Rel 1.0 so will have to be addressed in another release.

**Comment by AlanSl** [comment]
Just discussed this with Colm - data from users who skip is not treated differently in being passed to the metrics service so I'll change the default for the first update.

Unless there are any objections or requests for something different I'll set the default to "Prefer not to say" which will allow us to use the existing translation, no new translations required.

**Comment by AlanSl** [comment]
Done, will be in next release
