### ISSUE TITLE
Content needs translation

### ISSUE THREAD

**Issue by fahd-arshad** [covid-alert-ny/covid-green-app#53]
@kevin-sheldon , can you kindly get the following content translated in the columns it is in? If possible this should be translated in the same file. If you need to break it up into smaller sheets, your call, but if the app changes and the number of labels changes, we'll have a lot of trouble mapping it back. It would be best if the translators can do their translations and put them in directly in the correct cells. Please ask the translators to use the InVision prototype to obtain context. Our goal would be to replace as much of the Google translations to be manually translated as possible. Also, maybe mark each cell's background green so that we can easily keep track of which cells are done and which aren't? Thank you.

https://docs.google.com/spreadsheets/d/1yxC3TaVjPuXtbHp7qWEG0t_7UZUQ7nOvWvxAQ5It5us/edit?ts=5f3cf952#gid=149430619

@colmharte can you kindly double-check that this is the most up-to-date set of labels? If the labels are changed, we need to carefully merge it into this file. If we can pull in the content from this file mid-week so we can test some of the manual translations, that'd be great.

**Comment by fahd-arshad** [comment]
@kevin-sheldon also note for the translations that the "\n" character they occasionally will see is translated as a linebreak. So "App\nSettings" forces the two words to be on different lines. The auto-translated labels are buggy in that the "\n" gets translated into "\ N". Because of the extra space, it no longer gets recognized as a line-break. So as translators translate, they should be mindful of keeping the \n's in the appropriate places after translation. Tks.

**Comment by floridemai** [comment]
@fahd-arshad @kevin-sheldon All languages have been updated and should be available in the current build (20).
All fields that were update or added are not in the build. Attaching the file that needs translating and also email it so it can be picked up asap. I'll close the ticket when those translations are sent back to be and app is updated to include them.

[ny-new-translations.xlsx](https://github.com/project-vagabond/covid-green-app/files/5145087/ny-new-translations.xlsx)

**Comment by kevin-sheldon** [comment]
Second round of translations with DOH translators are in progress. Will send them over to Paul as soon as we get them back.

**Comment by fahd-arshad** [comment]
We need to ask our translators if County names need to be translated, from both the symptom picker demographics question as well as the Data tab. Fahd is emailing Steve S.

**Comment by floridemai** [comment]
@fahd-arshad @kevin-sheldon Translations merged; they should be available in the next build. I think we should close this ticket down and open a separate one for the next round of translations (https://github.com/project-vagabond/covid-green-app/issues/319).

**Comment by fahd-arshad** [comment]
Closing this since the initial translations are done and we are doing QA under separate tickets.
