### ISSUE TITLE
Remove "amount of closeness cases: #" from the "Submit Feedback" metadata

### ISSUE THREAD

**Issue by fahd-arshad** [covid-alert-ny/covid-green-app#536]
The last row of the meta-data submitted in the "Submit Feedback" button is "amount of closeness cases: 0". We should remove this as business stakeholders agree that its technical value for debugging is not commensurate with the privacy loss.

**Comment by AlanSl** [comment]
Done, will be in next release

**Comment by kevin-sheldon** [comment]
Confirmed that this is no longer appearing on tech. diagnostics in e-mails.
