### ISSUE TITLE
Add support for right-to-left languages

### ISSUE THREAD

**Issue by fahd-arshad** [covid-alert-ny/covid-green-app#541]
We need RTL language support so we can add:
1. Yiddish
2. Arabic
3. Urdu

for improved localization for NYC.

**Comment by mattobee** [comment]
Translations for these new languages are being sourced in #551

**Comment by AlanSl** [comment]
This is in the `v1.1.0.52` build currently on TestFlight / beta Play Store.

**Comment by denisedresbach** [comment]
1.1.0.52 I see RTL for Yiddish (iOS/Android) but the other languages are not available yet. 
This ticket is for the support of RTL so I think it can be closed at this point.
