### ISSUE TITLE
Tabs don't respect the safe area for some iPhone users

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#542]
Tabs don't respect the safe area for some iPhone users
![image](https://user-images.githubusercontent.com/68069959/94931105-57867580-0495-11eb-9a98-a50c56c28d72.png)

So far two users with same specs.  This also came up in the SUNY field trial.
App Version: 1.0.1.50
Device: iPhone 11
OS version: ios 14.0

**Comment by AlanSl** [comment]
This is in the `v1.1.0.52` build currently on TestFlight / beta Play Store.

**Comment by ahurworth** [comment]
Thanks @AlanSl !  Unfortunately I can't test this as I haven't experienced it myself -- I was reporting it on behalf of a few people in the field trials who saw it.

**Comment by AlanSl** [comment]
@denisedresbach are you able to check this and close it, build 52 or 53? I know iPhone R 11 is one of the phones where this had happened but any with the microphone grill as pictured should be okay to confirm it's done.

**Comment by denisedresbach** [comment]
@AlanSl I wasn't able to test this one, but I can try to figure out how to get the microphone grill to test.

**Comment by AlanSl** [comment]
@denisedresbach If you don't have one of the right type of devices to hand don't worry about it, we have tested it so I think we can close this as done.
