### ISSUE TITLE
Update Store Listing to Indicate Additional Language Support

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#544]
Since Apple and Google Store listings don't support Haitian Creole and Bengali, we couldn't tag the app as supporting those, even though they are.  

We should add a sentence in the freeform text field to indicate they are in fact supported.  

@fahd-arshad @dharding 

This issue may not belong on this board, but tracking here so we don't lose it.

**Comment by fahd-arshad** [comment]
I believe this is done.
