### ISSUE TITLE
Translations to languages other than Russian and Chinese are not functioning

### ISSUE THREAD

**Issue by fahd-arshad** [covid-alert-ny/covid-green-app#55]
Translations are not working. For example, here are the translations for the "Back" button:

navbar.back | Back | Retounen | назад | পেছনে | 뒤 | 背部 | Espalda | 

If you just stay on the "My Language" page and switch to the first two languages after "English", the "Back" label does change. But if you go to the 4th language onwards ("Kreyol ayisyen"/Haitian Creole), the label switches back to the Russian version (lang #2, назад). If you navigate out, you will see that all the labels remain in Russian instead of translating to the specified language. Spanish maps back to English. 

Please fix to include at least Google translations of these languages while we obtain manual translations. Thank you.

**Comment by AlanSl** [comment]
Fixed in code, should be fixed in the next build (18?)

**Comment by fahd-arshad** [comment]
@mboskin may I leave this one with you to validate once it's in today's build? This was originally reported by Mahesh. Tks.

**Comment by mboskin** [comment]
AlanSI closed. I think it was corrected when the newest translation spreadsheet was loaded.

_____________________

www.nystec.com<http://www.nystec.com/>

**Comment by fahd-arshad** [comment]
This seems to work now.
