### ISSUE TITLE
Apply Yiddish translations to app

### ISSUE THREAD

**Issue by AlanSl** [covid-alert-ny/covid-green-app#554]
Part of https://github.com/covid-alert-ny/covid-green-app/issues/551

Spreadsheet containing Yiddish translations (dated 2020-10-16):

[covid-alert-ny-translations-v7-yi.xlsx](https://github.com/covid-alert-ny/covid-green-app/files/5393180/covid-alert-ny-translations-v7-yi.xlsx)

These came with a translator's note about lines starting with left-to-right characters being displayed in the spreadsheet  as left to right. That is discussed here: https://github.com/covid-alert-ny/covid-green-app/issues/555

**Comment by AlanSl** [comment]
Here are some screenshots of key screens in Yiddish for validation:

![Screenshot from 2020-10-16 16-05-32](https://user-images.githubusercontent.com/29628323/96288766-db834600-0fdb-11eb-92d5-2ffa2337d730.png) ![Screenshot from 2020-10-16 16-06-11](https://user-images.githubusercontent.com/29628323/96288768-dc1bdc80-0fdb-11eb-969f-d636c4434abd.png)
![Screenshot from 2020-10-16 16-06-52](https://user-images.githubusercontent.com/29628323/96288770-dc1bdc80-0fdb-11eb-9812-a65e19661b49.png) ![Screenshot from 2020-10-16 16-07-14](https://user-images.githubusercontent.com/29628323/96288771-dcb47300-0fdb-11eb-9cf9-ccf2ed13ff49.png)
![Screenshot from 2020-10-16 16-07-43](https://user-images.githubusercontent.com/29628323/96288773-dcb47300-0fdb-11eb-9c73-e1ba867b618e.png) ![Screenshot from 2020-10-16 16-08-02](https://user-images.githubusercontent.com/29628323/96288774-dd4d0980-0fdb-11eb-845d-31b1a3547dc8.png)
![Screenshot from 2020-10-16 16-08-15](https://user-images.githubusercontent.com/29628323/96288776-dd4d0980-0fdb-11eb-826a-1ad7259829f1.png) ![Screenshot from 2020-10-16 16-08-39](https://user-images.githubusercontent.com/29628323/96288778-dde5a000-0fdb-11eb-91cf-96b320c33775.png)

**Comment by AlanSl** [comment]
This is in the `v1.1.0.52` build currently on TestFlight / beta Play Store.

**Comment by denisedresbach** [comment]
I can change to Yiddish in 1.1.0.52 iOS and Android.
I have tested best I can and wrote up a couple tickets for issues found.
