### ISSUE TITLE
Ensure mixed LTR and RTL lines in RTL languages are displayed correctly

### ISSUE THREAD

**Issue by AlanSl** [covid-alert-ny/covid-green-app#555]
I'm posting this as an issue on its own rather than part of https://github.com/covid-alert-ny/covid-green-app/issues/551 for easy reference as it was raised by a translator:

> **Important note:** We found an issue with Microsoft Excel handling sentences with mixed Yiddish and English. I looked online for quite a while without success.
>
>
> When the text in the cell starts with English text or a symbol (asterisk, backslash, etc.). For example, the very first cell in the document, shows in Excel like this:
>
>
> ![image](https://user-images.githubusercontent.com/29628323/96288212-f1443b80-0fda-11eb-8570-485bccff0d27.png)
> 
> That is completely wrong, as it should show like this (from right to left):
> 
> ![image](https://user-images.githubusercontent.com/29628323/96288226-f7d2b300-0fda-11eb-8979-3c66b26a7386.png)
> 
> What Microsoft Excel does is to make the entire cell Left-to-right, but keep the Yiddish text Right-to-left.
>
>Another example is row 59 (starts with asterisk). The cell are aligned Left-to-right, however, the Yiddish text flows right to left. This can be very confusing, it shows like this in Excel:
>
> ![image](https://user-images.githubusercontent.com/29628323/96288292-15078180-0fdb-11eb-938f-73697f3abc80.png)
>
> But it should look like this:
>
> ![image](https://user-images.githubusercontent.com/29628323/96288318-1fc21680-0fdb-11eb-9ac8-906ff0f04e85.png)

**Comment by AlanSl** [comment]
It's a known issue which I encountered and have a working solution for while working on https://github.com/covid-alert-ny/covid-green-app/pull/549 

We handle it on import - it won't look how it does in Excel in the app. Essentially:

 - A paragraph's left-to-right or right-to-left orientation is derived from its initial characters, so a line like `"COVID تنبيه NY"` may be treated as left-to-right.
 - Unicode has tools for overriding this: the [right-to-left mark](https://en.wikipedia.org/wiki/Right-to-left_mark) and [left-to-right mark](https://en.wikipedia.org/wiki/Left-to-right_mark). These are invisible zero-width characters that change the orientation of blocks of characters immediately following them.
 - I've updated the import script we use to apply these automatically:
   - Applying a RTL marker to lines in RTL languages where a potentially LTR character starts a line or a block
   - Applying a LTR marker to markdown links (`[text label](http://example.com)`) so that they are readable in the JSON files, otherwise they can misleadingly appear to be broken 

There may also be some cases we need to apply these characters manually. Here's an example code block with the characters between the quotation marks for convenient copy-paste:

```js
const rtlMarkerChar = '‏';
const ltrMarkerChar = '‎';
```

**Comment by denisedresbach** [comment]
1.1.0.52 - I looked at all screens in the app that I have access to. I see sentences that start with COVID and they are on the right as expected.
@AlanSl One section I see the English word is on the left is in the About you section of My Health Log for the County selected.
Is this the same thing or should I write up a new ticket? 
![2020-10-29](https://user-images.githubusercontent.com/69995161/97631768-b2f14800-19ee-11eb-804b-21a189d66844.png)

**Comment by AlanSl** [comment]
There should be no more cases like this in build 53

**Comment by denisedresbach** [comment]
Verified fixed 1.1.0.53
