### ISSUE TITLE
Share link points to the wrong message and URL

### ISSUE THREAD

**Issue by fahd-arshad** [covid-alert-ny/covid-green-app#56]
If you share the app via text on iOS, the text that is generated references COVID Green and points to the Irish app. Can we kindly make it this:

Help keep your fellow NYers safe from COVID-19 by flattening the curve. Get the COVID Smart NY app: https://CovidSmartNY.health.ny.gov/. 

iOS 13.6, iPhone X, build 12

![2020-08-24 07 29 15](https://user-images.githubusercontent.com/68031284/91057669-5fbcdc80-e5dc-11ea-8ff6-bbb03b5718a9.png)

**Comment by fahd-arshad** [comment]
@floridemai sorry, we changed the URL on you since we filed this ticket. Would you mind redirecting the URL to https://CovidAlertNY.health.ny.gov/ instead of CovidSmart? Thank you. 

After fixing please assign to NYS folks to validate. I am not going to be able to test for the next few days. Tks.

**Comment by kevin-sheldon** [comment]
I retested this and it looks good from my end.
