### ISSUE TITLE
Access denied when clicking on Policy link in Yiddish

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#560]
App version: iOS Android 1.1.0.52
OS: iOS 14, Android 10
Device: iPhone SE, Pixel 3XL
Reproducible: Always

Summary: Change language to Yiddish and click on any of the Policy links results in Access denied message

Steps to reproduce:
1. Launch app go to Settings > Change language > Choose Yiddish
2. Go to Data Policy and click on link 

Actual Results: 
<Error>

<Code>AccessDenied</Code>

<Message>Access Denied</Message>

<RequestId>7F00FD9FFA972DB8</RequestId>

<HostId>SxcxWvpn5pbFGaRc8RYPz+PqXy7FS1wkQE55YGIFhHSUL7BxMTanrSlTIZOlWRNgda3n8rKla0k=</HostId>

</Error>

**Comment by AlanSl** [comment]
Looks like the translation included the old URL - I'll update it at the same time as adding the Arabic policy

**Comment by AlanSl** [comment]
I've passed on amended policies and I believe these are now added to the API, they should show in build 53 (maybe also live release) and both Yiddish and Arabic should work.

**Comment by denisedresbach** [comment]
Verified fixed for Yiddish 1.1.0.53 
For Arabic the link also works but the screen is in English. I will write up a ticket for that.
