### ISSUE TITLE
Changed language to Yiddish shows blank results for County and Age in My Health Log

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#561]
App version:Android 1.1.0.52
OS: , Android 10
Device: Pixel 3XL
Reproducible: 

Summary: Change language to Yiddish and click on My Health Log > County or age > Select and Save = Blank entry when viewing saved info.

Steps to reproduce:
1 Launch app go to Settings > Change language > Choose Yiddish
2 Go to My Health Log and enter county and age > Save
3 View the information saved

Actual Results: Age and County show blank
Workaround: Go to a different screen and come back to view selected and they show up 

![2020-10-28 (1)](https://user-images.githubusercontent.com/69995161/97484679-4dca2380-1916-11eb-8bca-ec2c2dcf00e6.png)
![2020-10-28](https://user-images.githubusercontent.com/69995161/97484682-4efb5080-1916-11eb-9e58-d500ed214507.png)

**Comment by AlanSl** [comment]
Should be fixed in build 53 (for Yiddish and Arabic)

**Comment by denisedresbach** [comment]
Verified fixed 1.1.0.53
