### ISSUE TITLE
Installing with Bluetooth off and not allowing notifications can get a user into a confusing place

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#563]
App version: iOS Android 1.1.0.52
OS: iOS 14, Android 10
Device: iPhone SE, Pixel 3XL
Reproducible: Always

Summary: 
Testing install while Bluetooth was off and attempting to skip all the notifications asking for it to be turned on. 
I see a little bit different of a result in iOS and could break this out into two tickets if needed.

For Android-After registered and enabling Bluetooth on my phone per instructions, the message doesn't refresh until I restart the app. It continues to tell me to enable Bluetooth even though I have it on. 

For iOS- Attempting to enable the settings by trying to follow the instructions is not working in a straightforward way.

Steps to reproduce: Android
1. Turn Bluetooth off
2. Install app
3. Onboard
4. When notifications is shown asking If you can Turn on COVID-19 Exposure Notifications Tap Cancel
5. On Closeness Sensing is not active screen is shown tap Set it up later and continue
COVID Alerts notifications are shown saying you must enable Bluetooth
6. Go to My COVID Alerts
7. Go to Settings and turn Bluetooth on
8. Go Back to app
Results: The Closeness Sensing is not active screen is shown
Expected: It is telling me that Bluetooth is not on but I just came from turning it on. I expect that message to go away.
9. Refresh screen - NY COVID Data or My COVID Alerts tab = message still says you must enable Bluetooth
10. Restart app
Results: Now the message has changed to You need to turn on COVID-19 Exposure Notifications and there is a button "Turn on" that does in fact turn it on. 

Steps for iOS:
1. Turn off BT from settings
2. Install app
3. Onboard tap continue but say Cancel for the Use COVID Alert NY for Exposure Notifications prompt
4. Tap Don't allow for COVID Alert NY Would like to send you notifications prompt
5. On Closeness Sensing is not enabled screen tap ok
6.  App can't alert you right now message is seen > Go to My COVID Alerts
7. Follow instructions on screen 1. go to App settings and enable Exposure Notifications 2. Go to Privacy > Health in your device's settings and make sure COVID-19 exposure logging  is on 
8. This could be my user error but I try to navigate to app settings > exposure notifications > and tap inactive but I cannot make it active. So then I go to No Active Region and I see NY in the list I tap on that and then tap Set As Active Region
Results: Nothing happens
Expected: Should it set to active and all will be well? It seems like I am stuck now.
Results for #2 - I went to Privacy > Health and couldn't find Exposure Logging in there.

Update: I closed the app and reopened.  Went to settings and was finally able to Set as active region. I had to tap on for Share in that same screen.
Now I am told to turn on Bluetooth when returning to the app.
I did this and see Notifications are disabled.
I then go back to settings and my COVID alerts are finally active!

**Comment by denisedresbach** [comment]
https://share.icloud.com/photos/0PsRo4Gc5_l5rUIXIDFg5GZkg

**Comment by AlanSl** [comment]
Hi @denisedresbach : 

 - For the Android issue, it seems to be working for me now, on returning to the app after enabling bluetooth the screen shows status as disabled for a moment then refreshes and shows enabled. Does it work for you in latest build or are there still problems?
 - For the iOS issue, I also struggled with it until I flipped the "Share Exposure Information" switch from "off" to "on". After doing this, the "set as active region" button worked. I'm not sure there's much we can do about this unfortunately as it's all on Apple's side, except maybe update the text to include something like "check that 'Share Exposure Information' is on" (which would require new translations). Can you please try to replicate the problem as above and then check this switch - if that solves it I'll enquire as to whether we want to update the text for the next release.

**Comment by denisedresbach** [comment]
@AlanSl 
For Android, when I go thru the steps above I still see exactly the same results as I did before. I am on 1.1.0.52 still.
The 'Please turn on Bluetooth' message is still shown unless I restart the app.
Note: If I restart the app, turn off Bluetooth and start app I see the message to turn BT on. If I turn on BT and go back and sit and wait for a few seconds, I do eventually see the message go away and Active is shown. Perhaps the install flow is key here?

For iOS, Yep, When I turn on Share Exposure Info the Set Active does work now. So update to instructions would be helpful.

**Comment by AlanSl** [comment]
Android issue should be fixed in 1.1.0.56

iOS issue: we'd need to go through a process to get wording approval, translations etc, might be possible for next release but also iOS side might change so it'd be good to separate that out as a backlog issue.

**Comment by denisedresbach** [comment]
Verified 1.1.0.57 This is fixed for Android. Now I can turn Bluetooth on and the message is cleared.
I turn on Closeness and all is right.

I will create a new ticket for iOS.
