### ISSUE TITLE
Some English seen when language set to Arabic

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#572]
App version: iOS Android 1.1.0.53
OS: iOS 14, Android 10
Device: iPhone SE, Pixel 3XL
Reproducible: Always

Summary: Some English seen when language set to Arabic

Steps to reproduce:
1. Launch app and go to settings
2. Change language to Arabic 

Policy screen is in English when language set to Arabic
Delete Data has a few English words
![IMG_0419](https://user-images.githubusercontent.com/69995161/99327336-921e5480-282e-11eb-956d-a356eac037eb.PNG)
![IMG_0418](https://user-images.githubusercontent.com/69995161/99327340-92b6eb00-282e-11eb-932a-1182181df251.PNG)

**Comment by AlanSl** [comment]
@denisedresbach The first screenshot, that's what the translator provided us. I'll double-check but it seems legit reflecting things the user might see in English.

The second one means that the version you have isn't getting the translated text from the API - @colmharte are those migrations applied to the server these builds use?

**Comment by colmharte** [comment]
Migrations have now ben applied
