### ISSUE TITLE
Add English to yi and ar language switcher text

### ISSUE THREAD

**Issue by AlanSl** [covid-alert-ny/covid-green-app#573]
> When I switch to Spanish for example and look at the settings menu, “My Language” is in parenthesis. This helps a user get back to this setting if they clicked on a different language by mistake.
> 
> If I switch to Yiddish or Arabic, I don’t see the “My Language” in parenthesis.

**Comment by AlanSl** [comment]
In latest build

**Comment by denisedresbach** [comment]
verified 1.1.0.54
