### ISSUE TITLE
Device is set to Arabic and App is in English when onboarding

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#574]
App version: Android 1.1.0.53
OS: Android 11
Device: Google Pixel 3XL
Reproducible: Always
Note: iOS worked as expected, on-boarding was not in English.

I tried setting my Android device language to Arabic so I can onboard with device already set. 
Results: The app is still in English during onboard 
Expected: App language should detect language and display in that language
See screenshot for the language I chose (there are many to choose from)
Note: In screenshot I have it at 2nd level but I had it in first position when testing this

![image](https://user-images.githubusercontent.com/69995161/99446010-3e197b80-28d3-11eb-87e1-d8a78c520913.png)

**Comment by AlanSl** [comment]
Should be fixed in latest build

**Comment by denisedresbach** [comment]
Verified fixed 1.1.0.54 Device in Arabic and install onboard is too
