### ISSUE TITLE
Arabic/Yiddish: Once you get an exposure alert and try to delete data, the app does not start over properly

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#575]
App version: Android 1.1.0.53
OS: Android 11
Device: Google Pixel 3XL
Reproducible: Always

Summary:  App is in Arabic or Yiddish and I received an exposure alert. If I delete data to reset app it takes me to the first screen to onboard and then I see the exposure alert screen show up. At this point the app gets unstable sometimes freezes. I have to quit the app to get it to work again. If I am in other languages it doesn't seem to happen.

Steps:
1. Launch app and go to Settings > My language and change to Yiddish or Arabic
2. Wait for Close Contact Alert and tap notification
3. Once you see the exposure screen Go Back 
4. Go to Settings > Delete Data and wait for a few seconds after confirming delete

Results: 
The "I confirm" screen will show for a second and then the Exposure Landing screen pops up again now in English.
There is no date for the message. 
At this point I can scroll down but the back button does not work and it seems stuck. 
One time I even saw part of the tabs show up and it was totally frozen.

Expected: Once you delete data it should not show exposure alert or freeze up 

Workaround: Quit app and start it up again 

Note: I tested this in Spanish and English and it did not show the exposure landing screen or freeze up.

![2020-11-17](https://user-images.githubusercontent.com/69995161/99490063-ec4a1300-291d-11eb-8a59-66a40fd5916d.png)

**Comment by AlanSl** [comment]
@denisedresbach When you have this problem, if you pull down the notification pane, is there a "Checking exposure keys" notification active, either when the app freezes up or after restarting the app?

**Comment by denisedresbach** [comment]
@AlanSl Yes and I noticed it was checking exposure keys for a long time, over 20 mins at least. I can test again to get exact if you want.

**Comment by AlanSl** [comment]
That's enough info thanks - if it's anything like what I've been seeing when I've successfully replicated this it'd be a very long wait (I often have to restart the phone). I should have enough info to fix this now but it'll be a tricky one.

**Comment by AlanSl** [comment]
(also slightly off topic @denisedresbach but on that device do the device tabs always look like the screenshot above, with the icons cropped off, or is that only when this bug happens?)

**Comment by denisedresbach** [comment]
@AlanSl No the screenshot with tabs seems to happen because I interact with it by swiping to the side as it loaded or when it loaded the exposure screen. If I don't touch it the tabs don't show up it just kinda seems stuck.

**Comment by denisedresbach** [comment]
Testing this out in 1.1.0.55 - The issue seems to be fixed, but I do see a bit of flashing screens going by as I wait for the I confirm screen. @AlanSl Is that something you would expect to happen?
[videoplayback.zip](https://github.com/covid-alert-ny/covid-green-app/files/5576559/videoplayback.zip)

Looks like the above happens with any language and doesn't matter if you have an alert. Maybe a little more flashy with RTL languages though.

**Comment by AlanSl** [comment]
Should be fixed in 1.1.0.56 (including the flashing issue, should be much cleaner now)

**Comment by denisedresbach** [comment]
1.1.0.57 This looks a lot better now! Testing iOS and Android
RTL and LTR

**Comment by phindmarsh** [comment]
This is likely totally unrelated, but in New Zealand we just released an update include EN and users are reporting the "Checking exposure keys" notification hanging around persistently. This is the only other issue I've found reporting a similar thing, although not in the same context. 

@AlanSl did you manage to create any conditions that cause that "checking exposure keys" notification to show up for a prolonged period? We are struggling to reproduce it here, any suggestions appreciated!

**Comment by AlanSl** [comment]
Hi @phindmarsh, thanks for getting in touch. Do you have an issue tracking this on the NZ app repo? If you do (or if you can open one) can you ping me in it please, and I'll share anything relevant that I find.

On that issue on the NZ repo, it would be good to see in particular if you have any information about when users are seeing this - for example, is it the first time they open the app after updating, or every time, or intermittently? Is it only on Android or is there also an issue on iOS? And, does your production app build have the 1.1.x or 1.2.x React Native Exposure Notification Service, and does it use the v1 or [v2 (new in 1.2.x)](https://github.com/covidgreen/react-native-exposure-notification-service/pull/55) ENS score calculation method?

On our side, we've only seen this on either dev builds or beta test builds, only on Android (no iOS equivalent), and almost always on switching back to a previously used app after testing another COVID app (but we didn't find a consistent or reliable way to replicate it). This was on 1.1.x React Native Exposure Notification Service, I'm hoping to have some time to thoroughly test 1.2.x later this week.
