### ISSUE TITLE
When I search for Brooklyn in counties it doesn't show up even though it is in the list

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#578]
App version: 1.1.0.55
iOS and Android

1. Launch app and tap on counties
2. Search for Brooklyn

Results: No results found for this search. Try with something else.
Expected: Brooklyn is in the list for Kings county so I would expect it to show 
Also, Is "Try with something else." the expected sentence here?

![2020-11-20](https://user-images.githubusercontent.com/69995161/99862415-898b8e00-2b4e-11eb-9fc6-f8a7afa9da7e.png)
![2020-11-20 (3)](https://user-images.githubusercontent.com/69995161/99862418-8a242480-2b4e-11eb-9d97-e660e4e3ab00.png)

**Comment by AlanSl** [comment]
Should be fixed in 1.1.0.56

**Comment by denisedresbach** [comment]
Verified 1.1.0.57 Brooklyn comes up in search now. I also tested this in Large display/font.
