### ISSUE TITLE
Health log UI date format

### ISSUE THREAD

**Issue by stuartgiles** [covid-alert-ny/covid-green-app#58]
It should be [Mmm dd]

3-letter months (Jan, Feb, Mar,...)
no period but a space
1/2 digits for the day
no “th” or “st” afterwards

Please see
https://app.zeplin.io/project/5f23ee3d1eb2f9215942942b/screen/5f3bab5e6b97a59e9ce9c13d

**Comment by fahd-arshad** [comment]
Confirmed that this is done in build 13.
