### ISSUE TITLE
Unable to test upload and share close contact codes: There was an error validating the code. Please try again

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#583]
Summary: I am getting an error after entering codes (iOS and Android build 56). There was an error validating the code. Please try again

App version: 1.1.0.56 iOS and Android

1. Launch app and go to My COVID Alerts
2. Share Your Close Contact Codes - enter a valid or invalid code
Results: There was an error validating the code. Please try again

**Comment by AlanSl** [comment]
Fixed in 1.1.0.57?

**Comment by denisedresbach** [comment]
Verified this is fixed 1.1.0.57 iOS and Android
