### ISSUE TITLE
iOS- Installing with Bluetooth off and not allowing notifications can get a user into a confusing place

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#585]
App version: iOS 1.1.0.57
OS: iOS 14
Device: iPhone SE
Reproducible: Always

Copied from Installing with Bluetooth off and not allowing notifications can get a user into a confusing place #563

Summary: iOS- Installing with Bluetooth off and not allowing notifications can get a user into a confusing place

For iOS- Attempting to enable the settings by trying to follow the instructions is not working in a straightforward way.

Steps to reproduce: 
1. Turn off BT from settings
2. Install app
3. Onboard tap continue but say Cancel for the Use COVID Alert NY for Exposure Notifications prompt
4. Tap Don't allow for COVID Alert NY Would like to send you notifications prompt
5. On Closeness Sensing is not enabled screen tap ok
6.  App can't alert you right now message is seen > Go to My COVID Alerts
7. Follow instructions on screen 1. go to App settings and enable Exposure Notifications 2. Go to Privacy > Health in your device's settings and make sure COVID-19 exposure logging  is on 
8. This could be my user error but I try to navigate to app settings > exposure notifications > and tap inactive but I cannot make it active. So then I go to No Active Region and I see NY in the list I tap on that and then tap Set As Active Region
Results: Nothing happens
Expected: Should it set to active and all will be well? It seems like I am stuck now.
Results for #2 - I went to Privacy > Health and couldn't find Exposure Logging in there.

Update: I closed the app and reopened.  Went to settings and was finally able to Set as active region. I had to tap on for Share in that same screen.
Now I am told to turn on Bluetooth when returning to the app.
I did this and see Notifications are disabled.
I then go back to settings and my COVID alerts are finally active!

**Comment by AlanSl** [comment]
@hizo There's some discussion here https://github.com/covid-alert-ny/covid-green-app/issues/563 - I think this just needs an update to the instructions

**Comment by denisedresbach** [comment]
Verified new instructions 1.1.1.63
