### ISSUE TITLE
Invalid codes: Shouldn't it validate before letting me share?

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#586]
App version: Android and iOS 1.1.0.57
OS: Android 11 iOS 14
Device: Google Pixel 3XL iPhone SE
Reproducible: Always

Summary: User is allowed to share if they enter an invalid code, which results in an error occurred message

Steps to reproduce:
1. Launch app and go to My COVID Alerts > What to do if you test positive > Share codes
2. Enter invalid code and tap next

Results: An error occurred trying to upload
Expected: Should say "invalid code" on the screen before allowing me to share. 
I checked 1.0.2 in previous builds and see it does work as expected.

![2020-11-25 (5)](https://user-images.githubusercontent.com/69995161/100293833-d51cae00-2f39-11eb-9224-2baa02fa3a48.png)

**Comment by denisedresbach** [comment]
I think we can close this now ? @AlanSl

**Comment by AlanSl** [comment]
Yes if you're happy with it @denisedresbach
