### ISSUE TITLE
Clicking link with code doesn't get entered into app if user left app with invalid code

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#594]
App version: Android 1.1.1.61 (unable to test on iOS at this time)
OS: Android 11
Device: iPixel 3XL
Reproducible: Always

Summary: Clicking link with code doesn't get entered into app if user left app with invalid code

Steps:
1. Open app and go to My COVID Alerts > What to do if you test positive > Share your close contact codes
2. Enter an invalid code and don't exit the app
3. Send a new code to phone
4. Go to text message that has the link in it and click link
Results: App opens up to the last place you had entered an invalid code and still shows invalid code message
Expected: Get rid of the invalid code and enter the new code

**Comment by AlanSl** [comment]
Should be fixed in next build

**Comment by denisedresbach** [comment]
@AlanSl Tested this out on Android build 1.1.1.62 
Now it shows the invalid error for a second and then enters the new number and allows the user to continue.
I will leave this here in backlog until it is ready for QA column.

**Comment by AlanSl** [comment]
@denisedresbach It's ready, feel free to close if you're happy it's fixed

**Comment by denisedresbach** [comment]
I will retest once I can click on links again.

**Comment by denisedresbach** [comment]
Tested this one again and still looking good. 1.1.1.63 Android
