### ISSUE TITLE
NY COVID Data: latest date is Dec 7 on all the graphs

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#595]
App version: Android 1.1.1.61 iOS 1.1.1.60
OS: Android 11
Device: iPixel 3XL
Reproducible: Always

Summary: NY COVID Data: latest date is Dec 7 on all the graphs

Steps:
Open app and go to NY COVID Data tab
Look at each graph 

Results:  Latest date is Dec 7 on all the graphs
Expected: Today is Dec 16th so I would expect at least Dec 15th
![2020-12-16](https://user-images.githubusercontent.com/69995161/102416281-6073e700-3fae-11eb-82bf-b4d04de86f40.png)

**Comment by AlanSl** [comment]
The data seems to come through fine on `prd` so it looks like this is just something like the QA server stats lambda not having been run.

@dgonzalez Can you please confirm that this is QA env only and not something we need to do anything about, and close or fix accordingly

**Comment by denisedresbach** [comment]
As of 1.1.1.69 I see this is now updated. shows up to Jan 19 now.

**Comment by denisedresbach** [comment]
This was resolved
