### ISSUE TITLE
Share close contact codes results in "An error occurred trying to upload"

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#597]
App version: Android 1.1.1.61, iOS 1.1.1.60
OS: Android 11, iOS 14.2
Device: Pixel 3XL, iPhone SE
Reproducible: Always

Summary: Share codes results in "An error occurred trying to upload"

Steps:
Launch app and go to My COVID Alerts and Share a code
Results: Once you enter the code and share an error is seen
 "An error occurred trying to upload" 
The error shows up right after I say ok to Share
note: I did delete my random IDs

Colm Harte  11:05 AM
@Fiacc do you know what issuer we set up with APHL? Uploads are failing for below reason
"unable to validate diagnosis verification: app gov.ny.health.proximity has not authorized health authority issuer: gov.ny.exposure-notifications
11:05
gov.ny.exposure-notifications is from APHL verification server and I don’t see a way to change it

Colm Harte  11:14 AM
we have gov.ny.health.proximity setup

**Comment by AlanSl** [comment]
@denisedresbach Do you still see this with valid codes after the recent validation changes?

**Comment by denisedresbach** [comment]
@AlanSl I do still see this error. Tested with latest build 1.1.1.63 on iOS and Android. (8 digits)

Colm Harte  10:44 AM
this is an APHL config issue so is expected to fail

**Comment by denisedresbach** [comment]
Eventually I was able to upload so I think this can be closed now.
