### ISSUE TITLE
The second time a link is clicked results in no numbers displayed - desired behavior?

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#600]
App version: Android 1.1.1.61 (unable to test on iOS at this time)
OS: Android 11
Device: Pixel 3XL
Reproducible: Always

Summary: Click link with code and open with app, go back a screen in the app and click link again results in no numbers displayed

Steps:
1. Send a code to your phone where app is installed
2. Tap link with code in text and open in app
3. Screen opens "Share Your Close Contact Codes" with numbers and letters entered
4. Tap Back - goes to My COVID Alerts
5. Go back to text and tap the code again

Results: "Share Your Close Contact Codes" opens again but this time no numbers or letters
Expected: I was expecting it to be the same as before where it shows the numbers and letters entered but not sure what is actually desired behavior.
Note: If I click next it does appear to move forward, but not sure if it will work as we have another upload error issue that isn't fixed yet.
![2020-12-17](https://user-images.githubusercontent.com/69995161/102537508-df752800-405f-11eb-9ff2-709252479074.png)

**Comment by AlanSl** [comment]
@denisedresbach I can't replicate this currently, maybe it was fixed by one of the other bug fixes (probably same as https://github.com/covid-alert-ny/covid-green-app/issues/594 if so). If you can still replicate this when build 63 becomes available, can you please post a video?

**Comment by denisedresbach** [comment]
@AlanSl I will try to test this again once I can get links to my phone again. Is there a way to get a link other than sending to an actual phone?

**Comment by AlanSl** [comment]
@denisedresbach Sure, put a link in any app that presents it as a pressable link. For example if you open this page in a browser you should be able to press these:

6 character: https://us-ny.en.express/v?c=123ABC 
8 character: https://us-ny.en.express/v?c=1234ABCD 
16 character: https://us-ny.en.express/v?c=1234ABCD5678EFGH

Another easy way is to type / paste the link into a note in Google Keep or Apple Notes, save the note and re-open it so it displays as a pressable link. 

Or, to easily get links from a computer to both iOS and Android, send the links in a Slack message to yourself or Slackbot or save them in a draft email.

**Comment by denisedresbach** [comment]
@AlanSl thanks for the info again 
I was able to reproduce the original issue. It seems the important part is that it has to be a valid code. 
I did it first with an invalid code and I get the invalid message each time.

https://user-images.githubusercontent.com/69995161/103929570-59825500-50d2-11eb-89c7-1ecf87977847.mp4

**Comment by AlanSl** [comment]
Ahh, I think this is by design. 

The code has been validated and saved securely in the app, so all the user needs to do is press next to proceed. This behaviour has been set to be like this with a special status `uploadOnly` for when the code is already validated that doesn't show the input box. It behaves the same as if a user entered the code manually then pressed back. 

@colmharte Can you please confirm if the behaviour in the video in the comment above expected.

**Comment by colmharte** [comment]
This is correct behaviour

**Comment by AlanSl** [comment]
@denisedresbach Feel free to close this then if you're happy with everything else on this issue

**Comment by denisedresbach** [comment]
@AlanSl ok great thanks!
