### ISSUE TITLE
Delete Data instructions for iOS need to be updated

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#602]
App version: iOS 1.1.1.60
OS: 14.2
Device: iPhone SE
Reproducible: Always

Summary: Delete Data instructions for iOS seem wrong

Steps:
1. Launch app on iOS
2. Go to Settings > Delete Data and read instructions

Results: Instructions say to search for Exposure logging, but if I follow those instructions I get stuck right there.
I believe the text needs updating.

![image_123986672 (6)](https://user-images.githubusercontent.com/69995161/102564801-09930e00-4091-11eb-8b65-819d3184cbe0.JPG)
![image_123986672 (5)](https://user-images.githubusercontent.com/69995161/102564804-0ac43b00-4091-11eb-8039-db204568fc32.JPG)

**Comment by denisedresbach** [comment]
Verified fixed in build 1.1.1.63

**Comment by denisedresbach** [comment]
@hizo @AlanSl 
Minor thing I noticed. The instructions are good now. However, the last sentence says "To stop storing new codes, you should turn off "Exposure Logging". Is this correct? Should it tell you to turn off Exposure Notifications instead of Logging?

**Comment by hizo** [comment]
Correct @denisedresbach , will fix.

**Comment by denisedresbach** [comment]
Verified fixed 1.1.1.64
