### ISSUE TITLE
iOS: Should I be allowed to add numbers in different language?

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#613]
App version: iOS 1.1.1.64
OS: 14.2
Device: iPhone SE
Reproducible: Always

Summary: iOS: Should I be allowed to add numbers in different language?

Steps:
I have a button on my keyboard that lets me switch to different language 
1. Launch app and go to My COVID Alerts
2. What to do if tested positive > Share you close contact codes
3. Tap box to type in numbers
4. In the lower left there is a button to pick a different language > Select that button
5. Try to type in text box

Results: When I type using those characters they disappear 
Expected: Is that not supported?

![image_123986672 (13)](https://user-images.githubusercontent.com/69995161/104977876-7877c580-59b5-11eb-9ac0-37e56480f893.JPG)

**Comment by AlanSl** [comment]
In the latest build, other script numbers will be allowed, but the codes will not contain them so it's not something the user would need to do.

The important thing is, if the device is set to Arabic and defaults to Arabic numbers, can you switch to and input western-style numbers?

**Comment by denisedresbach** [comment]
@AlanSl Yep I can get to western style number keyboard when device is in Arabic - after 8 characters I get the full keyboard
