### ISSUE TITLE
iOS: Clicking links on iPhone asks me what browser to open and doesn't have the app available to choose from

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#614]
App version: iOS 1.1.1.64
OS: iOS 14.2
Device: iPhone SE
Reproducible: Always

Summary: iOS: iOS: Clicking links on iPhone asks me what browser to open and doesn't have the app available to choose from

Steps:
1. Send a link with code to iPhone
2. Tap link 

Results: I am asked what browser I want to open the link with and if I choose one I get a message that says unable to verify link
Expected: On Android I see the NY app available in the list to choose to open. 

![image_123986672 (14)](https://user-images.githubusercontent.com/69995161/104978453-b5908780-59b6-11eb-854d-1155e2f1df9c.JPG)

**Comment by AlanSl** [comment]
This will be the case until APHL upload a validation file to their server. I don't know when that will happen and don't have visibility on that - @colmharte can you re-open this for testing when it's done?

**Comment by denisedresbach** [comment]
This was resolved 1/19/21. I will test and close with new build to be sure.
