### ISSUE TITLE
Better message for attempting to share codes when device is offline 

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#617]
App version: 1.1.1.64
OS: iOS 14.2, Android 11
Device: iPhone SE, Pixel 3 XL
Reproducible: Always

Summary: If user is offline and tries to share a code, the message says there was an error instead of telling them they are offline

Steps:
1. Put phone into airplane mode
2. Open app and try to share a close contact code

Results: There was an error validating your code. Please try again.
Expected: Let user know they are offline.

![image_123986672 (15)](https://user-images.githubusercontent.com/69995161/104979655-a7903600-59b9-11eb-96a1-cd03617487de.JPG)

**Comment by AlanSl** [comment]
Should be fixed in the next build

**Comment by denisedresbach** [comment]
Verified 1.1.1.67 
Message now says: Connection issue. Please check your internet connection and try again.
Tested both links and manual.
Saw some minor issues and I can write those up for future.
