### ISSUE TITLE
When display is large, is it possible to make the codes easier to read ?

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#621]
iOS 1.1.1.64
Accessibility Display size set to largest

6 or 8 characters: I can see the first 4 and it is difficult to navigate to see the full set. Not sure if anyone will want to do this, but just something I wondered about.

![image_123986672 (16)](https://user-images.githubusercontent.com/69995161/105096012-53d62900-5a5b-11eb-9e45-a2c197378bb8.JPG)

16 characters: This doesn't show all the numbers but it does show 14 of them. This is also difficult to try to tap and see all the numbers. It wants to select all. Maybe that is user error?

![image_123986672 (17)](https://user-images.githubusercontent.com/69995161/105096079-6e100700-5a5b-11eb-80fe-6ce5f5ea9e3a.JPG)

**Comment by AlanSl** [comment]
Should be fixed in the next build

**Comment by denisedresbach** [comment]
1.1.1.67

![2021-01-20 (1)](https://user-images.githubusercontent.com/69995161/105246103-a11fcc80-5b27-11eb-9a2f-e7e92f39d0a5.jpeg)
![2021-01-20](https://user-images.githubusercontent.com/69995161/105246105-a250f980-5b27-11eb-8954-ed6104cbb163.jpeg)
