### ISSUE TITLE
Android: Display/Font is set to largest results in keyboard covering the code text field a little 

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#628]
App version: 1.1.1.67
OS: Android 11
Device: Pixel 3 XL
Reproducible: Always

Summary: Android: Display/Font is set to largest results in keyboard covering the code text field a little 

Steps:
1. Set device and font size to largest in Accessibility menu
2. Open up app and go to My Covid Alerts and start typing 

Results: keyboard covers up the text field some

![2021-01-20](https://user-images.githubusercontent.com/69995161/105246760-8f8af480-5b28-11eb-97ff-dd95ae822a62.png)

**Comment by AlanSl** [comment]
Should be fixed in next build.

**Comment by denisedresbach** [comment]
Verified 1.1.1.69 Now I can scroll to see the full text field iOS and Android
