### ISSUE TITLE
Is this desired behavior? First 8 characters shows number keypad and as you go past 8 it changes to full keyboard

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#629]
App version: 1.1.1.67
OS: Android 11 iOS 14.3
Device: Pixel 3 XL iPhone SE
Reproducible: Always

Summary: Is this desired behavior? First 8 characters shows number keypad and as you go past 8 it changes to full keyboard

Steps: 
1. Open app and go to My COVID Alerts
2. Go to Share codes and start entering codes 
= Number keypad is shown
3. Go beyond 8 characters

Results: Changes to full keyboard after 8 char.
Also, if you go delete more than 8 char it switches back to number keypad which feels kind of odd.
The above is really odd during screen reader too but I am using invalid codes at the moment.
Expected? 

![2021-01-20 (2)](https://user-images.githubusercontent.com/69995161/105247643-f5c44700-5b29-11eb-800b-6cc9732fdb5c.png)
![2021-01-20 (1)](https://user-images.githubusercontent.com/69995161/105247649-f78e0a80-5b29-11eb-803b-ba7180aa72af.png)

**Comment by AlanSl** [comment]
There isn't really any good option here, but as a least-worst option I've set it to always show alphanumeric keyboard.

**Comment by denisedresbach** [comment]
1.1.1.69 I always get the full keyboard now.
