### ISSUE TITLE
Pasting codes from text results in invalid code (changes it to all caps when I paste) and I cannot type them out

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#630]
App version: 1.1.1.67
OS: Android 11 iOS 14.3
Device: Pixel 3 XL iPhone SE
Reproducible: Always

Summary: Now that we allow typing 16 characters or pasting the 16 characters I am running into a couple of issues:

1. If I copy paste just the code from SMS and submit, it is invalid - Perhaps the reason is because once I paste it makes it all caps? When I do it by the link it is lowercase and is ok with it
2. I can't type the number letter combo because of https://github.com/covid-alert-ny/covid-green-app/issues/629
Unless the code started out w only 8 numbers

Workaround: Just use the link :)

**Comment by AlanSl** [comment]
In next build

**Comment by denisedresbach** [comment]
Verified 1.1.1.69 Android and iOS- I can paste the code in and type it out. One small thing that could be a problem is when I type in iOS the first letter is uppercase when it needs to be lower. You can back up and fix it though.
