### ISSUE TITLE
Subject for feedback emails says version [object Object]

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#631]
App version: 1.1.1.67
OS: iOS 14.2, Android 11
Device: iPhone SE, Pixel 3 XL
Reproducible: Always

Summary: Subject for feedback emails says version [object Object]

1. Launch app and go to Settings > Submit Feedback
2. Tap one of the type of feedback buttons

Results: "Version [object Object]" is seen in the subject

![2021-01-20 (4)](https://user-images.githubusercontent.com/69995161/105268931-e48a3300-5b47-11eb-9627-83f979197a41.png)

**Comment by AlanSl** [comment]
In next build

**Comment by denisedresbach** [comment]
Verified 1.1.1.69
