### ISSUE TITLE
List of issues seen with VoiceOver and TalkBack while testing 1.1.1.69 

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#635]
App version: 1.1.1.69
OS: iOS 14.2, Android 11
Device: iPhone SE, Pixel 3 XL
Reproducible: Always

Summary: List of issues seen with VoiceOver and TalkBack while testing 1.1.1.69 

iOS
Screens that have links to testing sites and phone numbers - some are not called out as links and some don't actually do anything when double tapped. Found on page after checking in on the Thank you screen with symptoms.
-Contact a health care provider reads as paragraph and cannot tap to dial
-For NYC: Call the Test & Trace paragraph same as above
-Find a site near you is not called a as a link and when I tap it opens to the site but I can't get back to app. 
-When I try to swipe back to get to the Done link it keeps going back to the address line.
-Also, it read phone number 227 minus 5,045 

Android - Share code screen- When you tap the number do you want it to read back like a full number? Example for code 123456 is read as 123 thousand 4 hundred 56.

Remaining issues from #618 

Android -After entering a valid code it says "keyboard hidden". Would be better for it to tell user it was accepted, workaround is to read the screen back to get new info and move to next button. (iOS read next screen automatically)

iOS - I type 6 or 8 char that is invalid and then swipe right to have voiceOVer find the next button, the ok button. Then I double tap on screen to say ok.
It would be nice if the error is read to me automatically (Android does). What it does now is says "code input text field is editing" then it reads the code to me along with some other instructions about correcting misspelled words. 1.1.1.69 still happens for me. 
Video is in #618 comments

**Comment by AlanSl** [comment]
IOS:

- _"Contact a health care provider reads as paragraph and cannot tap to dial"_ - **Can't replicate**, the text "Contact a health care provider" is just bold text and the phone number below does work as a link and offers to call
- _"For NYC: Call the Test & Trace paragraph same as above"_ - **Can't replicate**, same as above, the text is just text but the number works as a telephone link
- _"Find a site near you is not called a as a link and when I tap it opens to the site but I can't get back to app."_ - **Can't replicate**, it reads as "Find a site near you - link"; it opens a web page and there is a "done" button in the top left of the in-app browser which returns to the app. Swipe-back gesture doesn't return to the app but that's system behaviour of the iOS in-app browser which we can't control.
- _"When I try to swipe back to get to the Done link it keeps going back to the address line."_ - This is how Apple designed the in app browser and it's **not something we can control**. For me, a single-finger left swipe from the address bar goes to the "done" button
- _"Also, it read phone number 227 minus 5,045"_ - Can replicate, and we can fix this by giving tel links an accessibility label like "1 2 3 4 5" etc with spaces, **should be fixed be in next build**.
- Old code error issue from  https://github.com/covid-alert-ny/covid-green-app/issues/618 - I still can't replicate but in the video it looks like you're closing the keyboard after pressing the button so in the next build I've set it to re-focus the error message if there is one after pressing "done" on the keyboard - for me it's already focussed without this but hopefully this will fix it on your device to. 

Which iOS version are you on, what device and what VoiceOver settings? I'm wondering why we might be seeing so many different results. I'm on default VoiceOver settings, iPhone SE, iOS 14.3.

**Comment by AlanSl** [comment]
Android:

- _"Share code screen- When you tap the number do you want it to read back like a full number? Example for code 123456 is read as 123 thousand 4 hundred 56."_ This is not something we can control like we can with the tel links because it's system behaviour to read the text input value and apply default assumptions about how to read it, it's not something we can control unfortunately, accessibility labels are ignored
- _"After entering a valid code it says "keyboard hidden""_ - as before I can't currently get codes validated and can't replicate simulating codes being validated and it sounds like system behaviour but I'll have another look as a lower priority

**Comment by denisedresbach** [comment]
@AlanSl I always try to put iOS version and device at top of all bugs if you ever need that info. 
OS: iOS 14.2
Device: iPhone SE
My VoiceOver settings should be default - Anything in particular I should look for? 

As far as reproducing I am at a loss here. I am looking at this now with latest build 1.1.1.71 and it is working fine for the first couple of issues. Perhaps there is a fix in now that makes it better? Or maybe I was stuck in-between some weird VoiceOver world?

I was able to reproduce this multiple times yesterday when testing in 1.1.1.69. 
One thing I am noticing that is different is, if I am on the screen with links and phone numbers, and I toggle back and forth between voiceover on and off, I see the paragraphs move and separate from links. Here is a video of what I am talking about
https://user-images.githubusercontent.com/69995161/105553738-d27cd180-5cba-11eb-8fcd-1190ab73901a.MOV
When I saw these items not clickable yesterday, I saw them connected to each other and it would only read the entire paragraph.  
Seems ok now. Except not being able to click done but that sounds like it is out of our control.

**Comment by denisedresbach** [comment]
Update: Seeing the same issues on Android that were reported on iOS. After trying a few different times now it works as expected!

Earlier I was able to see the issue in Android with TalkBack where it would lump these links and phone numbers in with a paragraph and would not allow me to click on them any longer. Now it is working as expected and I can select everything. Perhaps this has to do with switching between using TalkBack or VoiceOver off and on while app is open and maybe sometimes it doesn't switch over properly? Either way, I think this is low priority. Maybe something for me to investigate further when there is a break in work.

**Comment by AlanSl** [comment]
Sounds like what's happening is the content is showing with the screen reader disabled, then the screen reader is enabled and it's not re-rendering with split paragraphs as it would with the screen reader enabled when the screen is loaded. Can you confirm that everything works fine if the user has the screen reader enabled from the start?

If so we can mark this as valid but low priority. I recently consolidated the screen reader detecting logic since we had it duplicated in multiple places in the app and it sounds like the consolidated version doesn't detect changes during a session as well as it did (but this is low priority since we'd expect a typical screen reader user to not frequently toggle off and on while using an app).

**Comment by denisedresbach** [comment]
@AlanSl Looking over 1.1.1.71 - Yep confirmed. If I set VoiceOver on and then open app I am not seeing the issues reported here. 
The one issue that I can reproduce all of the time is when I go to the Find testing site link, I get stuck in the browser on iOS. I believe you could not reproduce that one and it wasn't under your control?

**Comment by AlanSl** [comment]
@denisedresbach What's the status here? I think we discussed the browser issue and agreed it's out of our control and by design by Apple - can we close this?

**Comment by denisedresbach** [comment]
@AlanSl Yes. sounds like nothing we can do here so I will close.
