### ISSUE TITLE
Settings / My Covid Alerts on iOS, the Turn on Bluetooth message is displayed even when Bluetooth is on

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#638]
App version: iOS 1.1.1.72
OS: iOS 14.4
Device:  iPhone SE
Reproducible: Always

Summary: Settings / My Covid Alerts on iOS, the Turn on Bluetooth message is displayed even when Bluetooth is on

![2021-02-01](https://user-images.githubusercontent.com/69995161/106495678-da820180-6470-11eb-8dc0-0a30510066ab.jpeg)

**Comment by denisedresbach** [comment]
Closing here since I moved it to the new board https://trello.com/c/6eS1OH0v

**Comment by AlanSl** [comment]
@denisedresbach That Trello board is private and this repo is public and open source so it's best to keep an open equivalent issue here until the issue is fixed

**Comment by denisedresbach** [comment]
Verified iOS 14.4 When Bluetooth is on there is no message to have your Bluetooth on. When Bluetooth is off the message to turn on Bluetooth is shown. 1.1.2.74
