### ISSUE TITLE
DOH UAT - My COVID Alerts "Setup" Button Not Working to Enable Closeness Sensing (HIGH)

### ISSUE THREAD

**Issue by kevin-sheldon** [covid-alert-ny/covid-green-app#64]
iOS 13.6
iPhone XS Max
Build: 1.0.0 (13)

If you skip onboarding process ("Skip for now" button) and do not enable Exposure Notifications, the "Setup" button does not work to allow you to enable Exposure Notifications at a later time. If you then try to enable My COVID Alerts via the Settings option, there is no option to enable Exposure Notifications. 

![MYCOVIDALERT_1](https://user-images.githubusercontent.com/69158966/91204189-b0623180-e6d1-11ea-8d5f-26dab2d8bf40.jpeg)

![MYCOVIDALERT_2](https://user-images.githubusercontent.com/69158966/91204233-c4a62e80-e6d1-11ea-8218-224958d23d05.jpeg)

![MYCOVIDALERT_3](https://user-images.githubusercontent.com/69158966/91204251-ccfe6980-e6d1-11ea-981f-c63ff1de5c45.jpeg)

**Comment by floridemai** [comment]
Will be close when https://github.com/project-vagabond/covid-green-app/issues/67 is finished

**Comment by kevin-sheldon** [comment]
Retested. Fix confirmed.
