### ISSUE TITLE
DOH UAT - Closeness Sensing Confirmation Screen Still Appears When You Click "Don't Enable" for EN (MEDIUM)

### ISSUE THREAD

**Issue by kevin-sheldon** [covid-alert-ny/covid-green-app#65]
While going through onboarding screens, if you click "Don't Enable" for Exposure Notification prompt, the next screen says that Closeness Sensing is now active. However, once you "Done", it still says Closeness Sensing is not active (as expected). 

Need to remove success confirmation message if someone clicks "Don't Enable" for EN. 

![EN_DontEnable_1](https://user-images.githubusercontent.com/69158966/91206370-0dabb200-e6d5-11ea-965f-d1329ce8f174.jpeg)
![EN_DontEnable_2](https://user-images.githubusercontent.com/69158966/91206385-11d7cf80-e6d5-11ea-985d-76f07571feee.jpeg)

**Comment by floridemai** [comment]
Will be fixed by https://github.com/project-vagabond/covid-green-app/issues/67

**Comment by kevin-sheldon** [comment]
Retested. Fix confirmed.
