### ISSUE TITLE
DOH UAT - Clicking "Device Settings" to Enable EN Does Not Bring You to Appropriate Settings Screen (HIGH)

### ISSUE THREAD

**Issue by kevin-sheldon** [covid-alert-ny/covid-green-app#66]
iOS 13.6
Build: 1.0.0 (13)

If you click on "Device Settings" to enable Exposure Notifications, it just brings you to the main iOS settings page. It should bring you directly to the settings screen to enable EN (Settings > Privacy > Health). If the user tries to enable or re-enable EN after the onboarding process, they will not know how to get to the screen to enable if it just brings them to the main iOS settings page. 
![DeviceSettings_1](https://user-images.githubusercontent.com/69158966/91206932-f4efcc00-e6d5-11ea-94b7-7a4175f54a53.jpeg)
![DeviceSettings_2](https://user-images.githubusercontent.com/69158966/91206939-f8835300-e6d5-11ea-8765-5025eb50ca39.jpeg)

**Comment by colmharte** [comment]
This is not possible, Apple don't allow deep linking into particular settings area.

**Comment by floridemai** [comment]
This will be solved in https://github.com/project-vagabond/covid-green-app/issues/67. On iOS we can only goto either "app settings" (for enabling ENS & Notification) or "device settings" and we need to explain the users what they need to access and what to do.

**Comment by kevin-sheldon** [comment]
@floridemai just noticed small typo on new instructions. 

Please fix "Privacy > Health Settigs" to "Privacy > Health Settings"

**Comment by AlanSl** [comment]
Typos fixed
