### ISSUE TITLE
DOH UAT - If you skip onboarding, iOS doesn't recognize any apps to enable EN (HIGH)

### ISSUE THREAD

**Issue by kevin-sheldon** [covid-alert-ny/covid-green-app#67]
iOS 13.6
XS Max
Build: 1.0.0 (13)

If you have app installed and you skip enabling exposure notifications during onboarding, you cannot go into your settings and turn on EN, because iOS does not recognize any Active Apps
![DeviceSettings3](https://user-images.githubusercontent.com/69158966/91207522-dd651300-e6d6-11ea-8ce2-dbeb09698a74.jpeg)

**Comment by fahd-arshad** [comment]
Folks we need to decide if this is an Apple issue or our app's. Currently our app flow is broken because it points to "Device Settings" to fix this, and it can't be addressed without re-installing the app.

**Comment by colmharte** [comment]
@fahd-arshad This is our issues, if setup skip then the button on CT screen to enable should be initiating the OS prompts.

**Comment by floridemai** [comment]
@fahd-arshad I've started working on this covering all the possible use-cases. There were a few discrepancies in the design and I've talked with @stuartgiles about this.
The code logic (refactor to reuse the cards in both onboard complete & my covid alerts) is in there just waiting for clarifications and final text. Will continue as soon as I have those. Putting this on hold for the moment.

**Comment by kevin-sheldon** [comment]
This actually brings you to the correct app settings page now on iOS.
