### ISSUE TITLE
DOH UAT - "X" Buttons Do Not Work on Overlay Screens (MEDIUM)

### ISSUE THREAD

**Issue by kevin-sheldon** [covid-alert-ny/covid-green-app#69]
iOS 13.6
XS Max

Build: 1.0.0 (13)

When going through the My Health Log, either for the first time or trying to update through Settings, the "X" icon does not close the overlay screen and forces me to make a selection

**Comment by floridemai** [comment]
PR: https://github.com/project-vagabond/covid-green-app/pull/84

**Comment by floridemai** [comment]
@kevin-sheldon That should be fixed in the next release. I think it will be 1.0.0 (14)

**Comment by kevin-sheldon** [comment]
Retested and fix has been confirmed.
