### ISSUE TITLE
Device connectivity check fails on iOS

### ISSUE THREAD

**Issue by dharding** [covid-alert-ny/covid-green-app#7]
When running on iOS, the `NetInfo` module is not accurately detecting device connectivity.

See: https://github.com/react-native-community/react-native-netinfo/issues/352

(as a temporary workaround I have removed the check for `isInternetReachable` and only use `isConnected` otherwise it is not possible to advance in the app at all)

**Comment by floridemai** [comment]
@dharding Is this still an issue?

**Comment by AlanSl** [comment]
@dharding I see you removed this from "To do", can we close it as Done?

**Comment by davidjharding** [comment]
Do not close this. We do not need to handle this for launch as it seems to work on device as is. I want to look into this more, I think it may have been an issue related to registering the device that was manifesting as a lack of connectivity.
