### ISSUE TITLE
DOH UAT - My Health Log Not Saving If You Close App (HIGH)

### ISSUE THREAD

**Issue by kevin-sheldon** [covid-alert-ny/covid-green-app#71]
Build 1.0.0 (13)
Tested on both iOS and Android

If you submit your responses for My Health Log for the day, and close out of the app (not delete, but full app close) then restart, the current submission deletes and user is forced to start over again.

**Comment by AlanSl** [comment]
Fixed in https://github.com/project-vagabond/covid-green-app/pull/86

The code that loads the saved data from past check-ins was using a different key to the code that saves it, so it missed the saved data on restarting the app.

**Comment by kevin-sheldon** [comment]
Retested and fix has been confirmed.
