### ISSUE TITLE
DOH UAT - Bottom Buttons Disappear (Intermittent) When You Skip Onboarding (MEDIUM)

### ISSUE THREAD

**Issue by kevin-sheldon** [covid-alert-ny/covid-green-app#72]
Build: 1.0.0 (13)
Android OS

When user skips Onboarding, the bottom options on the screen do not appear. Forced user to close down app and restart to see the bottom icons/options. 

<img width="181" alt="Bottom Buttons" src="https://user-images.githubusercontent.com/69158966/91241670-7a45a180-e713-11ea-987d-07b103a38270.png">

**Comment by floridemai** [comment]
@kevin-sheldon Was not able to reproduce on Samsung S6 Edge (Android 7.0). Can you provide more details? What device. Anything else that could help in narrowing down the reasons.

**Comment by kevin-sheldon** [comment]
Retested and verified fix. Closing bug.
