### ISSUE TITLE
DOH UAT - "Find a Site Near You" URL Not Correct (HIGH)

### ISSUE THREAD

**Issue by kevin-sheldon** [covid-alert-ny/covid-green-app#73]
Build: 1.0.0 (13)
OS: Both iOS and Android

Within My Health Log, when you log enough qualifying symptoms, and you are brought to the screen with the "Find a Site Near You" link, the link brings you to google.ro instead of the appropriate provider page.

**Comment by AlanSl** [comment]
It looks like this has been fixed already. It gives the correct link for me in Android and it appears the link was updated:

- In code, it's corrected everywhere after https://github.com/project-vagabond/covid-green-app/pull/57 and https://github.com/project-vagabond/covid-green-app/pull/47
- In the API text, I've checked these:
  - https://api.dev.ctprox.health.ny.gov/api/settings
  - https://api.qa.ctprox.health.ny.gov/api/settings
  - https://api.prd.ctprox.health.ny.gov/api/settings

So unless there's another API address in use I'm unaware of (@colmharte @floridemai ?), I'm pretty sure this has been fixed.

**Comment by colmharte** [comment]
Yes this was fixed on Monday.

**Comment by kevin-sheldon** [comment]
correct URL now in place and verified by tester.
