### ISSUE TITLE
Change the name of the app from "COVID Smart NY" to "COVID Alert NY"

### ISSUE THREAD

**Issue by fahd-arshad** [covid-alert-ny/covid-green-app#74]
Kindly change  "COVID Smart NY" to "COVID Alert NY" in:

1. the app and prototype visuals 
2. all references in the copy of the app, and

Assigning to @stuartgiles as the first step. Stuart, NYS requested we archive the current artwork so we don't lose it entirely if a future comparison has to be made. Also, can we kindly make the changes to the InVision prototype as well *after* you take care of the app itself? We still have a number of eye-balls on this and leaving InVision unchanged will cause a ton of confusion. 

Thank you.

**Comment by kevin-sheldon** [comment]
Enhancement must be implemented before go-live. Thank You!

**Comment by davidjharding** [comment]
Do we have the logo assets for this? Can they be attached to this issue?

**Comment by stuartgiles** [comment]
I believe these are the only images that need to be replaced...
```
/ios/Assets.xcassets/AppLogo.imageset/app-logo.png
/ios/Assets.xcassets/AppLogo.imageset/app-logo@2x.png
/ios/Assets.xcassets/AppLogo.imageset/app-logo@3x.png
/src/assets/icons/app-logo.svg
```

I'm guessing the logo that appears in the app header bar is simply one of the above resized and cropped appropriately.
However, just in case, I have also supplied a specific SVG for it.

Logos attached here
[updated logos.zip](https://github.com/project-vagabond/covid-green-app/files/5138027/updated.logos.zip)

Please let me know if you spot anything else. I have no way of knowing what has been previously exported from my sketch file.

**Comment by davidjharding** [comment]
I have separated #74 and #115 to assign the work for me separately.

**Comment by floridemai** [comment]
@fahd-arshad This should be addressed in the next build... sorry but not sure which one :(

**Comment by kevin-sheldon** [comment]
This appears to be addressed. Fahd is out this weekend, so I am closing on his behalf. Will log new bug if we see any instances of "COVID SMART NY" left on any of the screens.
