### ISSUE TITLE
DOH UAT - Allowed to Put "Placeholder" Text in My Health Log Overlay (LOW)

### ISSUE THREAD

**Issue by kevin-sheldon** [covid-alert-ny/covid-green-app#76]
Build: 1.0.0 (13)
OS: Android

When using the search function in the My Health Log county picker, user was able to put in any text then hit the "X" button and the text still remained on the screen. User couldn't save entries though, likely because the word entered wasn't a valid county. This issue does not seem to exist on iOS. 

<img width="172" alt="Placeholder" src="https://user-images.githubusercontent.com/69158966/91242957-be867100-e716-11ea-974d-08317226cf83.png">

**Comment by AlanSl** [comment]
I can't replicate this on Android (9) - however I return, the search text is not shown in the main list.

Unless @floridemai can replicate this on iOS it looks like it was already fixed

**Comment by floridemai** [comment]
@AlanSl I can't replicate either. iPhone XS (13.6.1)

**Comment by kevin-sheldon** [comment]
tester retested and he can no longer put a placeholder text in.
