### ISSUE TITLE
DOH UAT - Can Log Multiple My Health Logs on Same Day (HIGH)

### ISSUE THREAD

**Issue by kevin-sheldon** [covid-alert-ny/covid-green-app#77]
Build: 1.0.0 (13)
OS:  Android

Android: Replicated by pressing 'I am feeling well today' then using the Back function of the Android device to return to the entry and pressing 'I am feeling well today'. Can be done multiple times and also with symptoms as long as 'Done' is not pressed on the next screen. Screenshot added.

iOS: You can also enter multiple logs. If you select "I am feeling well today"  then swipe the screen from left to right to go back, it will allow you to enter another log for the same day and saves multiple logs. 

<img width="171" alt="Multiple My Health Log" src="https://user-images.githubusercontent.com/69158966/91243461-1a052e80-e718-11ea-8b1e-1524de114453.png">

**Comment by AlanSl** [comment]
Fixed in https://github.com/project-vagabond/covid-green-app/pull/85 - swaps 'navigate' actions (which add to stack navigation history allowing going back) with 'replace' actions (which replace the checker page in the stack navigation history, preventing going back to it).

**Comment by kevin-sheldon** [comment]
Retested and fix has been confirmed on both iOS and Android.
