### ISSUE TITLE
Chart duration change

### ISSUE THREAD

**Issue by fahd-arshad** [covid-alert-ny/covid-green-app#78]
Please change the duration of charts to last 30 days instead of last 7 days.

**Comment by AlanSl** [comment]
App side: should be fixed in the next build now https://github.com/project-vagabond/covid-green-app/pull/87 is in

Also needs updates on the API side which I understand are in `dev` API currently

**Comment by fahd-arshad** [comment]
@ahurworth would you mind closing this out once this is verified to be in the build? Tks.

**Comment by AlanSl** [comment]
Checked today and the duration has been updated, which is good, but we're getting 29 days of data in the app instead of 30. I've asked @segfault to look into why this is happening on the API side.

**Comment by fahd-arshad** [comment]
@segfault can you kindly double-check why we are not getting the full 30 days of data flowing in? 

Also, please see the label issue at https://github.com/project-vagabond/covid-green-app/issues/79#issuecomment-684859295 if the two are related somehow.

**Comment by segfault** [comment]
It looks like max age is exclusive https://github.com/project-vagabond/covid-green-regional-lambdas/blob/current/stats.js#L35
I can bump the value and we should capture the last day.

**Comment by segfault** [comment]
I've bumped the cutoff value to 2,678,400,000 and I'm pulling in @mikegwhit to look at the code and underlying data.

**Comment by mikegwhit** [comment]
This should be fixed.  A test has been added to ensure the 30 day limit is the default.  Please revise issue such that it refers to pulling in SSM parameter if we are not getting 30 days.

CC @segfault @rgormley SSM should now only have to specify the number of days (instead of the number of milliseconds).  Please reach out if you want to coordinate.

**Comment by AlanSl** [comment]
This appears to be properly complete now. We're getting enough data in the app to show 30 days and to calculate 7-day rolling averages, but not so much that the download is slow.

**Comment by helloantoine** [comment]
Looks good to me.
