### ISSUE TITLE
Inconsistent behavior when Bluetooth is disabled (Android and iOS)

### ISSUE THREAD

**Issue by dharding** [covid-alert-ny/covid-green-app#8]
Repro steps:
- complete on-boarding flow, consenting to both EN and push notifications.
- land on app in "ready" state
- background the app
- turn off Bluetooth
==> On Android this triggers a push notification. On foregrounding the app, both platforms I see the app continues to report it is in the "contact tracing active" state.
==> On iOS I do not get a push notification.  On my installation, the app indicates it is still tracing.  My colleague's app does not present a push notification, but DOES indicate tracing is not happening and prompts the user to enable bluetooth.

Another tweak on this flow (I am seeing this behavior on iOS and Android):
- turn off Bluetooth
- then complete the onboarding.
==> I was expecting the app to turn on Bluetooth for me, or maybe prompt to tell me this is what it would do.  It does neither for me. The app reports is it contact tracing. 

Devices used: iPhone 11 Max Pro running 13.6; Pixel 4 XL running Android 10

**Comment by fahd-arshad** [comment]
@kevin-sheldon @mboskin Paul is going to provide some details on the *expected* behavior when toggling BT on and off. Can we kindly make these part of the UAT scripts? Thank you.

**Comment by mboskin** [comment]
When and how will Paul provide the details?

**Comment by mboskin** [comment]
When and how will Paul be providing the details of expected behavior?

_____________________

www.nystec.com<http://www.nystec.com/>

**Comment by colmharte** [comment]
Note that on android ens api does not report when Bluetooth is off so it is expected that app shows as tracing active.

On iOS there are 2 ways to disable Bluetooth, control panel on settings. Only when disabled is Bluetooth actually app and the app will the show tracing as inactive. Switching bluettoh off via control panel does not actually disable bluettoh, its just disables new connections

**Comment by floridemai** [comment]
> Note that on android ens api does not report when Bluetooth is off so it is expected that app shows as tracing active.
> 
> On iOS there are 2 ways to disable Bluetooth, control panel on settings. Only when disabled is Bluetooth actually app and the app will the show tracing as inactive. Switching bluettoh off via control panel does not actually disable bluettoh, its just disables new connections

There is nothing to add to this. Describes perfectly how the app behaves.

**Comment by fahd-arshad** [comment]
@colmharte @dharding regarding "Note that on android ens api does not report when Bluetooth is off so it is expected that app shows as tracing active." Would this be something we raise with Google then? What's the best way to move forward here? We probably don't want the situation where an Android user is given incorrect status.

**Comment by fahd-arshad** [comment]
@colmharte @dharding Do Android APIs let us directly query the status of BT? If so, can we get around this issue by checking both ENS and BT at least on Android, and if BT is off we know to warn the user that ENS is disabled, even though Android falsely claims that it isn't?

**Comment by colmharte** [comment]
We cannot query BT via ENS and cannot query BT directly. This issue can only be resolved if Google make the status of BT available through ENS. There is nothing more we can currently do with this so we should close this issue.

**Comment by fahd-arshad** [comment]
As per Colm's update above.

**Comment by mboskin** [comment]
This is on our list to be added. 

Regards
Colm

On Thu 3 Sep 2020, 20:44 Sheldon, Kevin M (HEALTH), <Kevin.Sheldon@health.ny.gov> wrote:
Hi Colm,
 
We had reached out to Google regarding the disabling of Bluetooth and impact to the app. Andrew had mentioned that they are able to query BT directly in their sample implementations, which I recall you mentioning that NF cannot do. 
 
Andrew had provided a link to the code here, and we wanted to see if you could take a look. Not alerting a user that their Bluetooth is disabled will defeat the main purpose of the app if they don’t realize that exposure notifications are not being logged.

**Comment by helloantoine** [comment]
I tested the cases reported originally.

**On iOS:**
> If you turn OFF BT (using Control Center), App does not detect the change and continue to say it's Active. 
> If you turn OFF BT (using Settings>Bluetooth), App does detect the change and shows the appropriate error. 
> If you turn OFF BT  (using Settings>Bluetooth) and start onboarding, it will tell you to turn ON Bluetooth at the end of onboarding.
Apple do NOT push a notification on the device when ENS is not active (unlike Android).

**On Android:**
> If you turn OFF BT, you get a system ENS message + the app now shows the BT error.

It is a pity Control Center BT does not behave like the Settings>BT but it's on Apple's side for now. Let's hope it get fixed soon.

I'm closing this.
