### ISSUE TITLE
Re-index the charts' y-axis to 0

### ISSUE THREAD

**Issue by fahd-arshad** [covid-alert-ny/covid-green-app#80]
Please re-index the charts' y-axis so it's minimum is always 0. Otherwise minor changes are misleadingly magnified.

**Comment by AlanSl** [comment]
Should be fixed in the next build now https://github.com/project-vagabond/covid-green-app/pull/87 is in

**Comment by fahd-arshad** [comment]
Tested on iOS build 16 and Android build 17. Looks good.
