### ISSUE TITLE
Switch charts to vertical bars

### ISSUE THREAD

**Issue by fahd-arshad** [covid-alert-ny/covid-green-app#81]
Switch the plot from line to bar charts. If possible, please calculate and overlay a trailing 7-day moving average as a line superimposed on the bars. The moving average needs to be captioned appropriately (Stuart can specify exactly how). If bar charts aren't possible, at a minimum turn off smoothing of the existing line plots. The line segments signal direction and magnitude of intraday change, and that signal is being lost with smoothing.

**Comment by AlanSl** [comment]
Should be fixed in the next build now https://github.com/project-vagabond/covid-green-app/pull/87 is in

**Comment by fahd-arshad** [comment]
Thank you for the quick switch to bar charts. 

The line should be 7-day **moving** average, calculated each day over the current day+trailing 6 days. This implies the line is unlikely to be flat but should change day to day. I'm assuming we are currently calculating a single average for the 7 days. 

If we can't do the moving average for the Columbia study, we should at least turn off this incorrect average line until we can do the moving average. 

After fixing kindly assign back to @ahurworth to validate. I will be unable to re-test until Tue.

**Comment by AlanSl** [comment]
The moving averages were coming out flat before because they were calculated from the data the API gave us, which at the time only provided 7 days of data.

We're now getting the full data and server-side average calculations since yesterday (build 20).

**Comment by kevin-sheldon** [comment]
@ahurworth were  you able to test  this from your end? I tested from my end and I see the appropriate bar charts with 7-day avg line.

**Comment by fahd-arshad** [comment]
The data is showing up properly. The visuals are being worked on in other tickets. Thank you!
