### ISSUE TITLE
Add positivity rate chart

### ISSUE THREAD

**Issue by fahd-arshad** [covid-alert-ny/covid-green-app#82]
Please add a new chart between the first and second charts titled "Percent tested positive". The formula should be: new_positives / total_number_of_tests * 100. Label the x-axis with %age to 1 decimal point (0.5%, 0.6%, 0.7%, etc).

**Comment by AlanSl** [comment]
The positivity rate charts have been present since (I think) build 17 and have had full data including rolling averages since build 20.

**Comment by fahd-arshad** [comment]
Thank you!
