### ISSUE TITLE
Minor Typos

### ISSUE THREAD

**Issue by mboskin** [covid-alert-ny/covid-green-app#93]
Found 8/26/2020 by Valerie Shuba on Android galaxy S10+. Screen captures attached
[Issue_14.pdf](https://github.com/project-vagabond/covid-green-app/files/5133237/Issue_14.pdf)

**Comment by floridemai** [comment]
@segfault You might want to have a look at this one as some of the typos are related to the policies content.

**Comment by segfault** [comment]
Thanks @floridemai . Hopefully it's all down to docx to markdown conversion artifacts.

**Comment by mboskin** [comment]
Is it ready for retest?

**Comment by AlanSl** [comment]
On the app side, yes. @segfault are the policies typos ready to retest on your side?

**Comment by fahd-arshad** [comment]
@mboskin can you kindly have this tested again and close out if all issues are resolved?

**Comment by segfault** [comment]
We should hopefully be good on this front. Do we have translations?

**Comment by mboskin** [comment]
Fahd,

Given these minor typos are grammar, do you think we need to get them retranslated?

Thanks,
Mike


www.nystec.com<http://www.nystec.com/>

**Comment by mboskin** [comment]
The English version was retested and passed. Other than the question about translation, this can be closed.

**Comment by fahd-arshad** [comment]
@mboskin yes, we do need this to be looked at again. I can see it fully translated in Bengali but none of the content is translated in Korean, or Spanish. We should recheck in all languages and translate. Privacy policy is important to get right.

**Comment by mboskin** [comment]
Steven,

Our testers found some minor typographical issues (attached) in the English language version of the app. Some of these are simply extraneous characters. Could you have your team check the translations to confirm that they were not included in the translations?

Thank you,


www.nystec.com<http://www.nystec.com/>

**Comment by helloantoine** [comment]
Closing it. The translation of the Privacy is captured elsewhere.
