### ISSUE TITLE
decimal place scale on y axis for Total tested and shows spikes for 1 or 2 people infected.

### ISSUE THREAD

**Issue by mboskin** [covid-alert-ny/covid-green-app#94]
August 26 at 4:23 by Francisco Torrales on Android LG K40

[4:55 PM] Sheldon, Kevin M (HEALTH)
    Please log that. Arshad, Fahd we should discuss with NF on a potential minimum Y axis value. Looking at the graph without axis labels, looks like Cayuga had a spike in positive cases, but it is only 1 person.
(1 liked)​[4:55 PM] Sheldon, Kevin M (HEALTH)
    Torrales, Francisco please log the decimal issue. I will discuss other thing mentioned above
![Screenshot-161559 (1)](https://user-images.githubusercontent.com/70291664/91369526-fc000280-e7d9-11ea-89da-b4dffe47dd7c.png)

**Comment by AlanSl** [comment]
Yes this is another one which is being addressed in https://github.com/project-vagabond/covid-green-app/pull/87 by setting the Y axis to have a max value of at least 5.

**Comment by AlanSl** [comment]
This should be in build 16 as part of the new charts

<img width=350 src="https://user-images.githubusercontent.com/29628323/91495089-e65e0c00-e8b1-11ea-99cb-c4ca13699859.jpg" />

**Comment by mboskin** [comment]
I know we synchronized the release numbers. Was today’s 16 or will 16 be tomorrow’s build?

Thanks

_____________________
Michael Boskin
Senior Consultant, NYSTEC
(518) 496-7667 – Mobile
mboskin@nystec.com<mailto:mboskin@nystec.com>

www.nystec.com<http://www.nystec.com/>

**Comment by mboskin** [comment]
Was build 16 posted for download today?

**Comment by colmharte** [comment]
Build 16 was today's release

**Comment by mboskin** [comment]
Thanks

_____________________

**Comment by AlanSl** [comment]
@mboskin Apparently something went wrong with Build 16 on Android and the old-style charts were still showing but the new-style ones should be present in Build 17 on Android, released just now (might not be available immediately)

**Comment by mboskin** [comment]
I appreciate your letting me know. Linh’s team will be retesting tomorrow.

Thanks,
Mike

_____________________

www.nystec.com<http://www.nystec.com/>

**Comment by mboskin** [comment]
Patrick Brennan | 9/1/20 5:30 PM | Pass | Results look clearer at a glance
