### ISSUE TITLE
Validate and Delete redundant labels for uploading random ids

### ISSUE THREAD

**Issue by fahd-arshad** [covid-alert-ny/covid-green-app#96]
As far as I can tell, the following labels are redundant and not used in the US version of the app. I checked the first 2, and the rest I am guessing based on the use of the terms "ID" (we tried not to use that) and "HSE". 

**Please confirm which of these are still needed for the NYS version, and kindly remove all else.** As of now the translators will not be translating any of these until @mboskin tells them otherwise based on this ticket's outcome. 

```
viewNames.uploadKeys | Upload Your Random Keys

uploadKeys.title | Upload your Random IDs
uploadKeys.code.intro | A member of the Contact Tracing team may ask you to share Random IDs generated by your phone over the previous 14 days.\n\nIf so, you will receive a unique 6-digit code by text message to activate the upload functionality.
uploadKeys.code.expiredError | Code has expired. Contact HSE to request another one.
uploadKeys.code.invalidError | Invalid code. Please try again.
uploadKeys.code.error | There was an error validating the code. Please try again.
uploadKeys.upload.intro | To assist us in tracing your recent contacts over the last 14 days, we are asking you to share your anonymous Random IDs generated by your phone with the HSE.
uploadKeys.upload.button | Upload your Random IDs to HSE
uploadKeys.permissionError | We have not uploaded your keys as you did not grant permission.
uploadKeys.uploadError | An error occurred trying to upload
uploadKeys.uploadSuccess.toast | Upload complete
uploadKeys.uploadSuccess.thanks | Thanks for uploading your Random Ids. This will help our contact tracing team to slow the spread of COVID-19 and protect others.
uploadKeys.uploadSuccess.updates | Return to Updates
```

**Comment by floridemai** [comment]
@fahd-arshad All of the above translations are used. What you have is the older version. Here is the link to the current text used in the app: https://github.com/project-vagabond/covid-green-app/blob/nys/src/assets/lang/en.json#L377

Invision links:
https://nearform.invisionapp.com/d/main#/console/20287854/428108353/preview
https://nearform.invisionapp.com/d/main#/console/20287854/428108354/preview

Here is a screenshot of the screen where we're using them:
![IMG_8040](https://user-images.githubusercontent.com/1158133/91440920-04a71600-e878-11ea-8544-2e9e9fd90da6.PNG)

**Comment by fahd-arshad** [comment]
@floridemai believes none of the ones I have listed here are in his current codebase, so closing this ticket.
