### ISSUE TITLE
Pls remove appStats card labels from codebase/translation export

### ISSUE THREAD

**Issue by fahd-arshad** [covid-alert-ny/covid-green-app#98]
I believe these labels are not part of the NYS design currently. Please verify and if I'm right, kindly remove them from the codebase or otherwise exclude them from your export script output so the translators do not waste time on these. 

appStats.title | Today's fight
appStats.totalCheckins | Total Check-Ins today
appStats.noSymptoms | Feeling good
appStats.someSymptoms | Some symptoms
appStats.nationalPicture | The national picture
appStats.breakdown | Tap for county breakdown

**Comment by AlanSl** [comment]
Yes, these are currently only used in the unused `app-stats` and `county-breakdown` cards.
